using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp.Application.Services;
using xdcb.FormServices.ModuleGroup.Dtos;

namespace xdcb.FormServices.ModuleGroups
{
	/// <summary>
	/// Generated IAppService for Table : ModuleGroup.
	/// </summary>
	public interface IModuleGroupAppService : IApplicationService
	{
		#region Generated By Column

		Task<List<ModuleGroupDto>> GetListAsync();

		Task<ModuleGroupDto> GetAsync(Guid id);

		Task<ModuleGroupDto> Create(CreateUpdateModuleGroupDto input);

		Task<ModuleGroupDto> Update(Guid id, CreateUpdateModuleGroupDto input);

		Task Delete(Guid id);

		#endregion
	}
}