//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FormQLVLocalizedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FormQLVLocalizedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("xdcb.FormQLV.Localization.FormQLVLocalizedResources", typeof(FormQLVLocalizedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới.
        /// </summary>
        public static string ActionCreate {
            get {
                return ResourceManager.GetString("ActionCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa.
        /// </summary>
        public static string ActionEdit {
            get {
                return ResourceManager.GetString("ActionEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kehoachtongnguondaunam_{0}.xlsx.
        /// </summary>
        public static string kehoachtongnguondaunam {
            get {
                return ResourceManager.GetString("kehoachtongnguondaunam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kehoachtongnguondieuchinhnam_{0}.xlsx.
        /// </summary>
        public static string kehoachtongnguondieuchinh {
            get {
                return ResourceManager.GetString("kehoachtongnguondieuchinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kehoachvontheongansachtinh_daunam_{0}.xlsx.
        /// </summary>
        public static string kehoachvontheongansachtinhdaunam {
            get {
                return ResourceManager.GetString("kehoachvontheongansachtinhdaunam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kehoachvontheongansachtinh_dieuchinh_{0}.xlsx.
        /// </summary>
        public static string kehoachvontheongansachtinhdieuchinh {
            get {
                return ResourceManager.GetString("kehoachvontheongansachtinhdieuchinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kehoachvontheonghiquyet_daunam_{0}.xlsx.
        /// </summary>
        public static string kehoachvontheonghiquyetdaunam {
            get {
                return ResourceManager.GetString("kehoachvontheonghiquyetdaunam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kehoachvontheonghiquyet_dieuchinh_{0}.xlsx.
        /// </summary>
        public static string kehoachvontheonghiquyetdieuchinh {
            get {
                return ResourceManager.GetString("kehoachvontheonghiquyetdieuchinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kehoachvontheongansachtrunguong_daunam_{0}.xlsx.
        /// </summary>
        public static string kehoachvontheoNSTWdaunam {
            get {
                return ResourceManager.GetString("kehoachvontheoNSTWdaunam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kehoachvontheongansachtrunguong_dieuchinh_{0}.xlsx.
        /// </summary>
        public static string kehoachvontheoNSTWdieuchinh {
            get {
                return ResourceManager.GetString("kehoachvontheoNSTWdieuchinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nhucaukehoachvonhangnam_daunam_{0}.xlsx.
        /// </summary>
        public static string nhucaukehoachvonhangnamdaunam {
            get {
                return ResourceManager.GetString("nhucaukehoachvonhangnamdaunam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nhucaukehoachvonhangnam_dieuchinh_{0}.xlsx.
        /// </summary>
        public static string nhucaukehoachvonhangnamdieuchinh {
            get {
                return ResourceManager.GetString("nhucaukehoachvonhangnamdieuchinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nhucaukehoachvontrunghan_daunam_{0}.xlsx.
        /// </summary>
        public static string nhucaukehoachvontrunghandaunam {
            get {
                return ResourceManager.GetString("nhucaukehoachvontrunghandaunam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nhucaukehoachvontrunghan_dieuchinh_{0}.xlsx.
        /// </summary>
        public static string nhucaukehoachvontrunghandieuchinh {
            get {
                return ResourceManager.GetString("nhucaukehoachvontrunghandieuchinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết công trình_Nhu cầu vốn giai đoạn {0} năm {1}.
        /// </summary>
        public static string TextFormNhuCauVonChiTiet {
            get {
                return ResourceManager.GetString("TextFormNhuCauVonChiTiet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0} giai đoạn {1} năm {2}.
        /// </summary>
        public static string TextGroupNhuCauVonChiTiet {
            get {
                return ResourceManager.GetString("TextGroupNhuCauVonChiTiet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} công trình.
        /// </summary>
        public static string TextPopUpCongTrinh {
            get {
                return ResourceManager.GetString("TextPopUpCongTrinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} giải ngân.
        /// </summary>
        public static string TextPopUpGiaiNgan {
            get {
                return ResourceManager.GetString("TextPopUpGiaiNgan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} kế hoạch tổng nguồn.
        /// </summary>
        public static string TextPopUpKeHoachVon {
            get {
                return ResourceManager.GetString("TextPopUpKeHoachVon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} kế hoạch vốn theo nghị quyết.
        /// </summary>
        public static string TextPopUpKeHoachVonNQ {
            get {
                return ResourceManager.GetString("TextPopUpKeHoachVonNQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} kế hoạch vốn theo ngân sách tỉnh.
        /// </summary>
        public static string TextPopUpKeHoachVonNST {
            get {
                return ResourceManager.GetString("TextPopUpKeHoachVonNST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} kế hoạch vốn theo ngân sách trung ương.
        /// </summary>
        public static string TextPopUpKeHoachVonNSTW {
            get {
                return ResourceManager.GetString("TextPopUpKeHoachVonNSTW", resourceCulture);
            }
        }
    }
}
