// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Volo.Abp.EntityFrameworkCore;
using xdcb.QuanLyVon.EntityFrameworkCore;

namespace xdcb.QuanLyVon.Migrations
{
    [DbContext(typeof(QuanLyVonMigrationsDbContext))]
    [Migration("20200717032318_initdbvon2")]
    partial class initdbvon2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("_Abp_DatabaseProvider", EfCoreDatabaseProvider.SqlServer)
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("xdcb.QuanLyVon.KeHoachTongNguonChiTiets.KeHoachTongNguonChiTiet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnName("ConcurrencyStamp")
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnName("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnName("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnName("DeleterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnName("DeletionTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DieuChinhGiam")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(22,6)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("DieuChinhTang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(22,6)")
                        .HasDefaultValue(0m);

                    b.Property<string>("ExtraProperties")
                        .HasColumnName("ExtraProperties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChuSoDauNam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChuSoDieuChinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChuUyBanDauNam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChuUyBanDieuChinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IsDeleted")
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal>("KeHoachBoSung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(22,6)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("KeHoachBoSungDuocDuyet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(22,6)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("KeHoachBoSungNamTruoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(22,6)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("KeHoachDauNam")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(22,6)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("KeHoachDauNamDuocDuyet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(22,6)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("KeHoachDauNamTruoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(22,6)")
                        .HasDefaultValue(0m);

                    b.Property<Guid>("KeHoachTongNguonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnName("LastModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnName("LastModifierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NguonVonChaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NguonVonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<string>("TenNguonVon")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("KeHoachTongNguonChiTiets","von");
                });

            modelBuilder.Entity("xdcb.QuanLyVon.KeHoachTongNguons.KeHoachTongNguon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnName("ConcurrencyStamp")
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnName("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnName("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnName("DeleterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnName("DeletionTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DinhKemFileDauNam")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("DinhKemFileDieuChinh")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("ExtraProperties")
                        .HasColumnName("ExtraProperties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChuDauNam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChuDieuChinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IsDeleted")
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal>("KeHoachDauNam")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(22,6)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("KeHoachDauNamDuocDuyet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(22,6)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("KeHoachSauBoSung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(22,6)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("KeHoachSauBoSungDuocDuyet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(22,6)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnName("LastModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnName("LastModifierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Nam")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayQuyetDinhDauNam")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayQuyetDinhDieuChinh")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<string>("SoQuyetDinhDauNam")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("SoQuyetDinhDieuChinh")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TrangThaiDauNam")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255)
                        .HasDefaultValue("");

                    b.Property<string>("TrangThaiDieuChinh")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255)
                        .HasDefaultValue("");

                    b.HasKey("Id");

                    b.ToTable("KeHoachTongNguons","von");
                });
#pragma warning restore 612, 618
        }
    }
}
