// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Volo.Abp.EntityFrameworkCore;
using xdcb.QuanLyVon.EntityFrameworkCore;

namespace xdcb.QuanLyVon.Migrations
{
    [DbContext(typeof(QuanLyVonMigrationsDbContext))]
    [Migration("20200911064746_Add_Column_Table_KeHoachTongNguonChiTiet")]
    partial class Add_Column_Table_KeHoachTongNguonChiTiet
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("_Abp_DatabaseProvider", EfCoreDatabaseProvider.SqlServer)
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("xdcb.QuanLyVon.KeHoachTongNguonChiTiets.KeHoachTongNguonChiTiet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnName("ConcurrencyStamp")
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnName("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnName("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnName("DeleterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnName("DeletionTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DieuChinhGiam")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(22,6)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("DieuChinhTang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(22,6)")
                        .HasDefaultValue(0m);

                    b.Property<string>("ExtraProperties")
                        .HasColumnName("ExtraProperties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChuSoDauNam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChuSoDieuChinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChuUyBanDauNam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChuUyBanDieuChinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleteDieuChinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IsDeleted")
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsSelectDieuChinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal>("KeHoachBoSung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(22,6)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("KeHoachBoSungDuocDuyet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(22,6)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("KeHoachBoSungNamTruoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(22,6)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("KeHoachDauNam")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(22,6)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("KeHoachDauNamDuocDuyet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(22,6)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("KeHoachDauNamTruoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(22,6)")
                        .HasDefaultValue(0m);

                    b.Property<Guid>("KeHoachTongNguonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnName("LastModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnName("LastModifierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NguonVonChaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NguonVonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<string>("TenNguonVon")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("KeHoachTongNguonChiTiets","von");
                });

            modelBuilder.Entity("xdcb.QuanLyVon.KeHoachTongNguons.KeHoachTongNguon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnName("ConcurrencyStamp")
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnName("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnName("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnName("DeleterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnName("DeletionTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DinhKemFileDauNam")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("DinhKemFileDieuChinh")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("ExtraProperties")
                        .HasColumnName("ExtraProperties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChuDauNam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChuDieuChinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IsDeleted")
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal>("KeHoachDauNam")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(22,6)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("KeHoachDauNamDuocDuyet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(22,6)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("KeHoachSauBoSung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(22,6)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("KeHoachSauBoSungDuocDuyet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(22,6)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnName("LastModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnName("LastModifierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Nam")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayQuyetDinhDauNam")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayQuyetDinhDieuChinh")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<string>("SoQuyetDinhDauNam")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("SoQuyetDinhDieuChinh")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TrangThaiDauNam")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255)
                        .HasDefaultValue("");

                    b.Property<string>("TrangThaiDieuChinh")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255)
                        .HasDefaultValue("");

                    b.HasKey("Id");

                    b.ToTable("KeHoachTongNguons","von");
                });

            modelBuilder.Entity("xdcb.QuanLyVon.NhuCauKeHoachVonChiTiets.NhuCauKeHoachVonChiTiet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnName("ConcurrencyStamp")
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.Property<Guid>("CongTrinhID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnName("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnName("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnName("DeleterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnName("DeletionTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DieuChinhGiamNST")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(22,6)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("DieuChinhGiamNSTW")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(22,6)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("DieuChinhGiamODA")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(22,6)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("DieuChinhTangNST")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(22,6)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("DieuChinhTangNSTW")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(22,6)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("DieuChinhTangODA")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(22,6)")
                        .HasDefaultValue(0m);

                    b.Property<string>("ExtraProperties")
                        .HasColumnName("ExtraProperties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChuChuyenVienDauNamNST")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChuChuyenVienDauNamNSTW")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChuChuyenVienDauNamODA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChuChuyenVienDieuChinhNST")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChuChuyenVienDieuChinhNSTW")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChuChuyenVienDieuChinhODA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChuDauNamNST")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChuDauNamNSTW")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChuDauNamODA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChuDieuChinhNST")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChuDieuChinhNSTW")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChuDieuChinhODA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IsDeleted")
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsSelect")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsSelectNST")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsSelectNSTW")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsSelectODA")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnName("LastModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnName("LastModifierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("LuyKeKhoiLuongNamTruocNST")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(22,6)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("LuyKeKhoiLuongNamTruocNSTW")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(22,6)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("LuyKeKhoiLuongNamTruocODA")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(22,6)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("LuyKeVonNamTruocNST")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(22,6)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("LuyKeVonNamTruocNSTW")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(22,6)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("LuyKeVonNamTruocODA")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(22,6)")
                        .HasDefaultValue(0m);

                    b.Property<Guid>("NhuCauKeHoachVonID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("NhuCauVonDauNamNST")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(22,6)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("NhuCauVonDauNamNSTW")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(22,6)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("NhuCauVonDauNamODA")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(22,6)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("NhuCauVonDieuChinhNST")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(22,6)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("NhuCauVonDieuChinhNSTW")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(22,6)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("NhuCauVonDieuChinhODA")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(22,6)")
                        .HasDefaultValue(0m);

                    b.Property<int>("OrderIndex")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("NhuCauKeHoachVonChiTiets","von");
                });

            modelBuilder.Entity("xdcb.QuanLyVon.NhuCauKeHoachVons.NhuCauKeHoachVon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChuDauTuID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnName("ConcurrencyStamp")
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnName("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnName("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnName("DeleterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnName("DeletionTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("DenNam")
                        .HasColumnType("int");

                    b.Property<string>("ExtraProperties")
                        .HasColumnName("ExtraProperties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GiaiDoanNam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IsDeleted")
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnName("LastModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnName("LastModifierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("OrderIndex")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenKeHoach")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255)
                        .HasDefaultValue("");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TongNhuCauVonDauNam")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(22,6)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("TongNhuCauVonDieuChinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(22,6)")
                        .HasDefaultValue(0m);

                    b.Property<string>("TrangThaiDauNam")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255)
                        .HasDefaultValue("");

                    b.Property<string>("TrangThaiDieuChinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255)
                        .HasDefaultValue("");

                    b.Property<int>("TuNam")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("NhuCauKeHoachVons","von");
                });
#pragma warning restore 612, 618
        }
    }
}
