using System;
using Volo.Abp.Application.Dtos;

namespace xdcb.QuanLyVon.GiaiNgan.Dtos
{
    /// <summary>
    /// Generated Contracts Dto for Table : GiaiNgan.
    /// </summary>
    public class GiaiNganDto : FullAuditedEntityDto<Guid>
    {
        #region Generated By Column

        public int Nam { get; set; }

        public int QuyThang { get; set; }

        public Guid ChuDauTuId { get; set; }

        public bool IsKeHoachKeoDai { get; set; }

        public string TenKeHoach { get; set; }

        public string TrangThai { get; set; }

        public decimal TongGiaiNgan { get; set; }

        public DateTime? NgayGui { get; set; }

        #endregion

        #region Extra property
        public string KeHoachGiaiNgan { get; set; }
        public int STT { get; set; }
        public int OrderIndex { get; set; }
        public string strNotification { get; set; }
        public string LoaiKeHoach { get; set; }
        public decimal CountChuDauTu { get; set; }
        public Guid CongTrinhId { get; set; }
        public int? intQuyThang { get; set; }
        #endregion
    }
}