using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp.Application.Services;
using xdcb.QuanLyVon.GiaiNganChiTiet.Dtos;

namespace xdcb.QuanLyVon.GiaiNganChiTiets
{
    /// <summary>
    /// Generated IAppService for Table : GiaiNganChiTiet.
    /// </summary>
    public interface IGiaiNganChiTietAppService : IApplicationService
    {
        #region Generated By Column

        Task<List<GiaiNganChiTietDto>> GetListAsync();

        Task<GiaiNganChiTietDto> GetAsync(Guid id);

        Task<GiaiNganChiTietDto> Create(CreateUpdateGiaiNganChiTietDto input);

        Task<GiaiNganChiTietDto> Update(Guid id, CreateUpdateGiaiNganChiTietDto input);

        Task Delete(Guid id);

        Task<List<GiaiNganChiTietDto>> GetListByGiaiNganIdAsync(Guid id);

        Task DeleteByGiaiNganId(Guid id);

        Task<List<GiaiNganChiTietDto>> GetListByLoaiKhoanIdAsync(Guid id);

        Task DeleteByLoaiKhoanId(Guid id);

        Task<List<GiaiNganChiTietDto>> GetListByLoaiCongTrinhIdAsync(Guid id);

        Task DeleteByLoaiCongTrinhId(Guid id);

        Task<List<GiaiNganChiTietDto>> GetListByCongTrinhIdAsync(Guid id);

        Task DeleteByCongTrinhId(Guid id);

        Task<List<GiaiNganChiTietDto>> GetListByKeHoachVonNSTChiTietIdAsync(Guid id);

        Task DeleteByKeHoachVonNSTChiTietId(Guid id);

        Task<List<GiaiNganChiTietDto>> GetListByKeHoachVonNSTWChiTietIdAsync(Guid id);

        Task DeleteByKeHoachVonNSTWChiTietId(Guid id);

        #endregion

        #region Extra Property
        Task<List<GiaiNganChiTietDto>> GetDataIsNew(int nam, Guid chuDauTuId);
        Task<List<GiaiNganChiTietDto>> GetDataDetailForTongHop(int nam, string tenkehoach, int? quyThang, bool? isKeHoachKeoDai, Guid congTrinhId);
        #endregion
    }
}