using System;
using System.Collections.Generic;
using System.Text;
using System.Threading.Tasks;
using Volo.Abp.Application.Services;
using xdcb.QuanLyVon.KeHoachVonNSTChiTiet.Dtos;

namespace xdcb.QuanLyVon.KeHoachVonNSTChiTiets
{
    public interface IKeHoachVonNSTChiTietAppService : IApplicationService
    {
        #region Generated By Column

        Task<List<KeHoachVonNSTChiTietDto>> GetListAsync();

        Task<KeHoachVonNSTChiTietDto> GetAsync(Guid id);

        Task<KeHoachVonNSTChiTietDto> Create(CreateUpdateKeHoachVonNSTChiTietDto input);

        Task<KeHoachVonNSTChiTietDto> Update(Guid id, CreateUpdateKeHoachVonNSTChiTietDto input);

        Task Delete(Guid id);

        Task<List<KeHoachVonNSTChiTietDto>> GetListByKeHoachVonNSTIdAsync(Guid id);

        Task DeleteByKeHoachVonNSTId(Guid id);


        Task<List<KeHoachVonNSTChiTietDto>> GetListByCongTrinhIdAsync(Guid id);

        Task DeleteByCongTrinhId(Guid id);

        Task<List<KeHoachVonNSTChiTietDto>> GetListByLoaiKhoanIdAsync(Guid id);

        Task DeleteByLoaiKhoanId(Guid id);

        #endregion

        #region Property
        Task DeleteKeHoachVonNSTDieuChinhChiTietById(Guid id);
        Task DeleteDataDieuChinhByKeHoachVonNSTID(Guid id);
        Task<List<KeHoachVonNSTChiTietDto>> GetDataLuyKeByNam(int nam);
        #endregion
    }
}
