using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp.Application.Services;
using xdcb.QuanLyVon.KeHoachVonNSTWChiTiet.Dtos;

namespace xdcb.QuanLyVon.KeHoachVonNSTWChiTiets
{
    /// <summary>
    /// Generated IAppService for Table : KeHoachVonNSTWChiTiet.
    /// </summary>
    public interface IKeHoachVonNSTWChiTietAppService : IApplicationService
    {
        #region Generated By Column

        Task<List<KeHoachVonNSTWChiTietDto>> GetListAsync();

        Task<KeHoachVonNSTWChiTietDto> GetAsync(Guid id);

        Task<KeHoachVonNSTWChiTietDto> Create(CreateUpdateKeHoachVonNSTWChiTietDto input);

        Task<KeHoachVonNSTWChiTietDto> Update(Guid id, CreateUpdateKeHoachVonNSTWChiTietDto input);

        Task Delete(Guid id);

        Task<List<KeHoachVonNSTWChiTietDto>> GetListByKeHoachVonNSTWIdAsync(Guid id);

        Task DeleteByKeHoachVonNSTWId(Guid id);

        Task<List<KeHoachVonNSTWChiTietDto>> GetListByLoaiKhoanIdAsync(Guid id);

        Task DeleteByLoaiKhoanId(Guid id);

        Task<List<KeHoachVonNSTWChiTietDto>> GetListByCongTrinhIdAsync(Guid id);

        Task DeleteByCongTrinhId(Guid id);

        #endregion

        #region Property
        Task DeleteKeHoachVonNSTWDieuChinhChiTietById(Guid id);
        Task DeleteDataDieuChinhByKeHoachVonNSTWID(Guid id);
        Task<List<KeHoachVonNSTWChiTietDto>> GetDataLuyKeByNam(int nam);
        #endregion
    }
}