using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp.Application.Services;
using xdcb.QuanLyVon.KeHoachVonNQChiTiet.Dtos;

namespace xdcb.QuanLyVon.KeHoachVonNQChiTiets
{
    /// <summary>
    /// Generated IAppService for Table : KeHoachVonNQChiTiet.
    /// </summary>
    public interface IKeHoachVonNQChiTietAppService : IApplicationService
    {
        #region Generated By Column

        Task<List<KeHoachVonNQChiTietDto>> GetListAsync();

        Task<KeHoachVonNQChiTietDto> GetAsync(Guid id);

        Task<KeHoachVonNQChiTietDto> Create(CreateUpdateKeHoachVonNQChiTietDto input);

        Task<KeHoachVonNQChiTietDto> Update(Guid id, CreateUpdateKeHoachVonNQChiTietDto input);

        Task Delete(Guid id);

        Task<List<KeHoachVonNQChiTietDto>> GetListByKeHoachVonNQIdAsync(Guid id);

        Task DeleteByKeHoachVonNQId(Guid id);

        Task<List<KeHoachVonNQChiTietDto>> GetListByNghiQuyetIdAsync(Guid id);

        Task DeleteByNghiQuyetId(Guid id);

        Task<List<KeHoachVonNQChiTietDto>> GetListByCongTrinhIdAsync(Guid id);

        Task DeleteByCongTrinhId(Guid id);

        #endregion

        #region Property
        Task DeleteKeHoachVonNQDieuChinhChiTietById(Guid id);
        Task DeleteDataDieuChinhByKeHoachVonNQID(Guid id);
        Task<List<KeHoachVonNQChiTietDto>> GetDataLuyKeByNam(int nam);
        #endregion
    }
}