using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp.Application.Services;
using xdcb.QuanLyVon.KeHoachVonNQ.Dtos;

namespace xdcb.QuanLyVon.KeHoachVonNQs
{
	/// <summary>
	/// Generated IAppService for Table : KeHoachVonNQ.
	/// </summary>
	public interface IKeHoachVonNQAppService : IApplicationService
	{
		#region Generated By Column

		Task<List<KeHoachVonNQDto>> GetListAsync();

		Task<KeHoachVonNQDto> GetAsync(Guid id);

		Task<KeHoachVonNQDto> Create(CreateUpdateKeHoachVonNQDto input);

		Task<KeHoachVonNQDto> Update(Guid id, CreateUpdateKeHoachVonNQDto input);

		Task Delete(Guid id);

		#endregion

		#region Property
		Task<List<KeHoachVonNQDto>> GetSearchData(int nam, string loaikehoach, string trangthai);
		Task DeleteKeHoachVonNQDieuChinh(Guid id);
		#endregion
	}
}