using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp.Application.Services;
using xdcb.QuanLyVon.KeHoachTongNguonChiTiet.Dtos;

namespace xdcb.QuanLyVon.KeHoachTongNguonChiTiets
{
	/// <summary>
	/// Generated IAppService for Table : KeHoachTongNguonChiTiet.
	/// </summary>
	public interface IKeHoachTongNguonChiTietAppService : IApplicationService
	{
		#region Generated By Column

		Task<List<KeHoachTongNguonChiTietDto>> GetListAsync();

		Task<KeHoachTongNguonChiTietDto> GetAsync(Guid id);

		Task<KeHoachTongNguonChiTietDto> Create(CreateUpdateKeHoachTongNguonChiTietDto input);

		Task<KeHoachTongNguonChiTietDto> Update(Guid id, CreateUpdateKeHoachTongNguonChiTietDto input);

		Task Delete(Guid id);

		Task<List<KeHoachTongNguonChiTietDto>> GetListByKeHoachTongNguonIdAsync(Guid id);

		Task DeleteByKeHoachTongNguonId(Guid id);

		Task<List<KeHoachTongNguonChiTietDto>> GetListByNguonVonIdAsync(Guid id);

		Task DeleteByNguonVonId(Guid id);

		Task<List<KeHoachTongNguonChiTietDto>> GetListByNguonVonChaIdAsync(Guid id);

		Task DeleteByNguonVonChaId(Guid id);

		#endregion

		#region extra property
		Task DeleteKeHoachVonDieuChinhById(Guid id);
		#endregion
	}
}