using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp.Application.Services;
using xdcb.QuanLyVon.KeHoachTongNguon.Dtos;

namespace xdcb.QuanLyVon.KeHoachTongNguons
{
    /// <summary>
    /// Generated IAppService for Table : KeHoachTongNguon.
    /// </summary>
    public interface IKeHoachTongNguonAppService : IApplicationService
    {
        #region Generated By Column

        Task<List<KeHoachTongNguonDto>> GetListAsync();

        Task<KeHoachTongNguonDto> GetAsync(Guid id);

        Task<KeHoachTongNguonDto> Create(CreateUpdateKeHoachTongNguonDto input);

        Task<KeHoachTongNguonDto> Update(Guid id, CreateUpdateKeHoachTongNguonDto input);

        Task Delete(Guid id);

        #endregion

        #region
        Task<List<KeHoachTongNguonDto>> GetSearchData(int nam, string loaikehoach, string trangthai);

        Task DeleteKeHoachVonDieuChinh(Guid id);
        #endregion
    }
}