using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp.Application.Services;
using xdcb.QuanLyVon.NhuCauKeHoachVonChiTiet.Dtos;

namespace xdcb.QuanLyVon.NhuCauKeHoachVonChiTiets
{
    /// <summary>
    /// Generated IAppService for Table : NhuCauKeHoachVonChiTiet.
    /// </summary>
    public interface INhuCauKeHoachVonChiTietAppService : IApplicationService
    {
        #region Generated By Column

        Task<List<NhuCauKeHoachVonChiTietDto>> GetListAsync();

        Task<NhuCauKeHoachVonChiTietDto> GetAsync(Guid id);

        Task<NhuCauKeHoachVonChiTietDto> Create(CreateUpdateNhuCauKeHoachVonChiTietDto input);

        Task<NhuCauKeHoachVonChiTietDto> Update(Guid id, CreateUpdateNhuCauKeHoachVonChiTietDto input);

        Task Delete(Guid id);

        Task<List<NhuCauKeHoachVonChiTietDto>> GetListByNhuCauKeHoachVonIDAsync(Guid id);

        Task DeleteByNhuCauKeHoachVonID(Guid id);

        Task<List<NhuCauKeHoachVonChiTietDto>> GetListByCongTrinhIDAsync(Guid id);

        Task DeleteByCongTrinhID(Guid id);
        #endregion

        #region Property
        Task DeleteDataDieuChinh(Guid id);
        Task<ResultExportDto> ExportDauNamByNhuCauKeHoachVonID(Guid nhuCauKeHoachVonID);
        Task<ResultExportDto> ExportDieuChinhHangNamByNhuCauKeHoachVonID(Guid nhuCauKeHoachVonID);
        Task<ResultExportDto> ExportDieuChinhTrungHanByNhuCauKeHoachVonID(Guid nhuCauKeHoachVonID);
        Task<List<NhuCauKeHoachVonChiTietDto>> GetListDataLuyKeByNhuCauKeHoachVonID(Guid nhuCauKeHoachVonID);
        Task<List<NhuCauKeHoachVonChiTietDto>> GetListDataByNhuCauVonIDAndCongTrinh(List<Guid> listnhuCauVonID, Guid congtrinhID);
        Task<NhuCauKeHoachVonChiTietDto> GetDataSumValueByNhuCauVonID(Guid nhuCauVonID);
        Task DeleteDataDieuChinhByNhuCauVonID(Guid id);
        #endregion
    }
}