using System;
using Refit;
using System.Collections.Generic;
using System.Threading.Tasks;
using xdcb.QuanLyVon.GiaiNganChiTiet.Dtos;

namespace xdcb.FormServices.SDK
{
    /// <summary>
    /// Generated ISDK for Table : GiaiNganChiTiet.
    /// </summary>
    public interface IGiaiNganChiTietsApi
    {
        #region Generated By Column

        [Get("/api/app/GiaiNganChiTiet")]
        Task<List<GiaiNganChiTietDto>> GetListAsync();

        [Post("/api/app/GiaiNganChiTiet")]
        Task<GiaiNganChiTietDto> Create([Body] CreateUpdateGiaiNganChiTietDto info);

        [Get("/api/app/GiaiNganChiTiet/{Id}")]
        Task<GiaiNganChiTietDto> GetAsync(Guid Id);

        [Put("/api/app/GiaiNganChiTiet/{Id}")]
        Task<GiaiNganChiTietDto> Update(Guid Id, [Body] CreateUpdateGiaiNganChiTietDto info);

        [Delete("/api/app/GiaiNganChiTiet/{Id}")]
        Task Delete(Guid Id);

        [Get("/api/app/giaiNgan/{id}/giaiNganChiTiet")]
        Task<List<GiaiNganChiTietDto>> GetListByGiaiNganIdAsync(Guid id);

        [Delete("/api/app/giaiNgan/{id}/giaiNganChiTiet")]
        Task DeleteByGiaiNganId(Guid id);

        [Get("/api/app/loaiKhoan/{id}/giaiNganChiTiet")]
        Task<List<GiaiNganChiTietDto>> GetListByLoaiKhoanIdAsync(Guid id);

        [Delete("/api/app/loaiKhoan/{id}/giaiNganChiTiet")]
        Task DeleteByLoaiKhoanId(Guid id);

        [Get("/api/app/loaiCongTrinh/{id}/giaiNganChiTiet")]
        Task<List<GiaiNganChiTietDto>> GetListByLoaiCongTrinhIdAsync(Guid id);

        [Delete("/api/app/loaiCongTrinh/{id}/giaiNganChiTiet")]
        Task DeleteByLoaiCongTrinhId(Guid id);

        [Get("/api/app/congTrinh/{id}/giaiNganChiTiet")]
        Task<List<GiaiNganChiTietDto>> GetListByCongTrinhIdAsync(Guid id);

        [Delete("/api/app/congTrinh/{id}/giaiNganChiTiet")]
        Task DeleteByCongTrinhId(Guid id);

        [Get("/api/app/keHoachVonNSTChiTiet/{id}/giaiNganChiTiet")]
        Task<List<GiaiNganChiTietDto>> GetListByKeHoachVonNSTChiTietIdAsync(Guid id);

        [Delete("/api/app/keHoachVonNSTChiTiet/{id}/giaiNganChiTiet")]
        Task DeleteByKeHoachVonNSTChiTietId(Guid id);

        [Get("/api/app/keHoachVonNSTWChiTiet/{id}/giaiNganChiTiet")]
        Task<List<GiaiNganChiTietDto>> GetListByKeHoachVonNSTWChiTietIdAsync(Guid id);

        [Delete("/api/app/keHoachVonNSTWChiTiet/{id}/giaiNganChiTiet")]
        Task DeleteByKeHoachVonNSTWChiTietId(Guid id);

        #endregion

        #region Extra Property
        [Get("/api/app/giaiNganChiTiet/dataIsNew/{chuDauTuId}")]
        Task<List<GiaiNganChiTietDto>> GetDataIsNew(int nam, Guid chuDauTuId);

        [Get("/api/app/giaiNganChiTiet/dataDetailForTongHop")]
        Task<List<GiaiNganChiTietDto>> GetDataDetailForTongHop(int nam, string tenkehoach, int? quyThang, bool? isKeHoachKeoDai, Guid congTrinhId);
        #endregion
    }
}