using System;
using Refit;
using System.Collections.Generic;
using System.Threading.Tasks;
using xdcb.QuanLyVon.KeHoachVonNQChiTiet.Dtos;

namespace xdcb.FormServices.SDK
{
    /// <summary>
    /// Generated ISDK for Table : KeHoachVonNQChiTiet.
    /// </summary>
    public interface IKeHoachVonNQChiTietsApi
    {
        #region Generated By Column

        [Get("/api/app/KeHoachVonNQChiTiet")]
        Task<List<KeHoachVonNQChiTietDto>> GetListAsync();

        [Post("/api/app/KeHoachVonNQChiTiet")]
        Task<KeHoachVonNQChiTietDto> Create([Body] CreateUpdateKeHoachVonNQChiTietDto info);

        [Get("/api/app/KeHoachVonNQChiTiet/{Id}")]
        Task<KeHoachVonNQChiTietDto> GetAsync(Guid Id);

        [Put("/api/app/KeHoachVonNQChiTiet/{Id}")]
        Task<KeHoachVonNQChiTietDto> Update(Guid Id, [Body] CreateUpdateKeHoachVonNQChiTietDto info);

        [Delete("/api/app/KeHoachVonNQChiTiet/{Id}")]
        Task Delete(Guid Id);

        [Get("/api/app/keHoachVonNQ/{id}/keHoachVonNQChiTiet")]
        Task<List<KeHoachVonNQChiTietDto>> GetListByKeHoachVonNQIdAsync(Guid id);

        [Delete("/api/app/keHoachVonNQ/{id}/keHoachVonNQChiTiet")]
        Task DeleteByKeHoachVonNQId(Guid id);

        [Get("/api/app/nghiQuyet/{id}/keHoachVonNQChiTiet")]
        Task<List<KeHoachVonNQChiTietDto>> GetListByNghiQuyetIdAsync(Guid id);

        [Delete("/api/app/nghiQuyet/{id}/keHoachVonNQChiTiet")]
        Task DeleteByNghiQuyetId(Guid id);

        [Get("/api/app/congTrinh/{id}/keHoachVonNQChiTiet")]
        Task<List<KeHoachVonNQChiTietDto>> GetListByCongTrinhIdAsync(Guid id);

        [Delete("/api/app/congTrinh/{id}/keHoachVonNQChiTiet")]
        Task DeleteByCongTrinhId(Guid id);

        #endregion

        #region #Property
        [Put("/api/app/keHoachVonNQDieuChinhChiTietById/{id}")]
        Task DeleteKeHoachVonNQDieuChinhChiTietById(Guid id);

        [Put("/api/app/keHoachVonNQ/{id}keHoachVonNQDieuChinhChiTiet")]
        Task DeleteDataDieuChinhByKeHoachVonNQID(Guid id);

        [Get("/api/app/keHoachVonNQChiTiet/dataLuyKeByNam")]
        Task<List<KeHoachVonNQChiTietDto>> GetDataLuyKeByNam(int nam);
        #endregion
    }
}