using Refit;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using xdcb.QuanLyVon.KeHoachVonNST.Dtos;

namespace xdcb.FormServices.SDK
{
    public interface IKeHoachVonNSTsApi
    {
        #region Generated By Column

        [Get("/api/app/KeHoachVonNST")]
        Task<List<KeHoachVonNSTDto>> GetListAsync();

        [Post("/api/app/KeHoachVonNST")]
        Task<KeHoachVonNSTDto> Create([Body] CreateUpdateKeHoachVonNSTDto info);

        [Get("/api/app/KeHoachVonNST/{Id}")]
        Task<KeHoachVonNSTDto> GetAsync(Guid Id);

        [Put("/api/app/KeHoachVonNST/{Id}")]
        Task<KeHoachVonNSTDto> Update(Guid Id, [Body] CreateUpdateKeHoachVonNSTDto info);

        [Delete("/api/app/KeHoachVonNST/{Id}")]
        Task Delete(Guid Id);

        #endregion Generated By Column

        #region Property

        [Get("/api/app/keHoachVonNST/searchData")]
        Task<List<KeHoachVonNSTDto>> GetSearchData(int nam, string loaikehoach, string trangthai);

        [Put("/api/app/KeHoachVonNSTDieuChinh/{id}")]
        Task DeleteKeHoachVonNSTDieuChinh(Guid id);

        #endregion Property
    }
}