using System;
using Refit;
using System.Collections.Generic;
using System.Threading.Tasks;
using xdcb.QuanLyVon.KeHoachVonNSTWChiTiet.Dtos;

namespace xdcb.FormServices.SDK
{
    /// <summary>
    /// Generated ISDK for Table : KeHoachVonNSTWChiTiet.
    /// </summary>
    public interface IKeHoachVonNSTWChiTietsApi
    {
        #region Generated By Column

        [Get("/api/app/KeHoachVonNSTWChiTiet")]
        Task<List<KeHoachVonNSTWChiTietDto>> GetListAsync();

        [Post("/api/app/KeHoachVonNSTWChiTiet")]
        Task<KeHoachVonNSTWChiTietDto> Create([Body] CreateUpdateKeHoachVonNSTWChiTietDto info);

        [Get("/api/app/KeHoachVonNSTWChiTiet/{Id}")]
        Task<KeHoachVonNSTWChiTietDto> GetAsync(Guid Id);

        [Put("/api/app/KeHoachVonNSTWChiTiet/{Id}")]
        Task<KeHoachVonNSTWChiTietDto> Update(Guid Id, [Body] CreateUpdateKeHoachVonNSTWChiTietDto info);

        [Delete("/api/app/KeHoachVonNSTWChiTiet/{Id}")]
        Task Delete(Guid Id);

        [Get("/api/app/keHoachVonNSTW/{id}/keHoachVonNSTWChiTiet")]
        Task<List<KeHoachVonNSTWChiTietDto>> GetListByKeHoachVonNSTWIdAsync(Guid id);

        [Delete("/api/app/keHoachVonNSTW/{id}/keHoachVonNSTWChiTiet")]
        Task DeleteByKeHoachVonNSTWId(Guid id);

        [Get("/api/app/loaiKhoan/{id}/keHoachVonNSTWChiTiet")]
        Task<List<KeHoachVonNSTWChiTietDto>> GetListByLoaiKhoanIdAsync(Guid id);

        [Delete("/api/app/loaiKhoan/{id}/keHoachVonNSTWChiTiet")]
        Task DeleteByLoaiKhoanId(Guid id);

        [Get("/api/app/congTrinh/{id}/keHoachVonNSTWChiTiet")]
        Task<List<KeHoachVonNSTWChiTietDto>> GetListByCongTrinhIdAsync(Guid id);

        [Delete("/api/app/congTrinh/{id}/keHoachVonNSTWChiTiet")]
        Task DeleteByCongTrinhId(Guid id);

        #endregion

        #region Property
        [Put("/api/app/keHoachVonNSTWDieuChinhChiTietById/{id}")]
        Task DeleteKeHoachVonNSTWDieuChinhChiTietById(Guid id);

        [Put("/api/app/keHoachVonNSTW/{id}/keHoachVonNSTWDieuChinhChiTiet")]
        Task DeleteDataDieuChinhByKeHoachVonNSTWID(Guid id);

        [Get("/api/app/keHoachVonNSTWChiTiet/dataLuyKeByNam")]
        Task<List<KeHoachVonNSTWChiTietDto>> GetDataLuyKeByNam(int nam);
        #endregion
    }
}