using System;
using Refit;
using System.Collections.Generic;
using System.Threading.Tasks;
using xdcb.QuanLyVon.KeHoachVonNSTW.Dtos;

namespace xdcb.FormServices.SDK
{
    /// <summary>
    /// Generated ISDK for Table : KeHoachVonNSTW.
    /// </summary>
    public interface IKeHoachVonNSTWsApi
    {
        #region Generated By Column

        [Get("/api/app/KeHoachVonNSTW")]
        Task<List<KeHoachVonNSTWDto>> GetListAsync();

        [Post("/api/app/KeHoachVonNSTW")]
        Task<KeHoachVonNSTWDto> Create([Body] CreateUpdateKeHoachVonNSTWDto info);

        [Get("/api/app/KeHoachVonNSTW/{Id}")]
        Task<KeHoachVonNSTWDto> GetAsync(Guid Id);

        [Put("/api/app/KeHoachVonNSTW/{Id}")]
        Task<KeHoachVonNSTWDto> Update(Guid Id, [Body] CreateUpdateKeHoachVonNSTWDto info);

        [Delete("/api/app/KeHoachVonNSTW/{Id}")]
        Task Delete(Guid Id);

        #endregion

        #region Property
        [Get("/api/app/KeHoachVonNSTW/searchData")]
        Task<List<KeHoachVonNSTWDto>> GetSearchData(int nam, string loaikehoach, string trangthai);

        [Put("/api/app/KeHoachVonNSTWDieuChinh/{id}")]
        Task DeleteKeHoachVonNSTWDieuChinh(Guid id);
        #endregion
    }
}