using System;
using Refit;
using System.Collections.Generic;
using System.Threading.Tasks;
using xdcb.QuanLyVon.KeHoachTongNguon.Dtos;

namespace xdcb.FormServices.SDK
{
    /// <summary>
    /// Generated ISDK for Table : KeHoachTongNguon.
    /// </summary>
    public interface IKeHoachTongNguonsApi
    {
        #region Generated By Column

        [Get("/api/app/KeHoachTongNguon")]
        Task<List<KeHoachTongNguonDto>> GetListAsync();

        [Post("/api/app/KeHoachTongNguon")]
        Task<KeHoachTongNguonDto> Create([Body] CreateUpdateKeHoachTongNguonDto info);

        [Get("/api/app/KeHoachTongNguon/{Id}")]
        Task<KeHoachTongNguonDto> GetAsync(Guid Id);

        [Put("/api/app/KeHoachTongNguon/{Id}")]
        Task<KeHoachTongNguonDto> Update(Guid Id, [Body] CreateUpdateKeHoachTongNguonDto info);

        [Delete("/api/app/KeHoachTongNguon/{Id}")]
        Task Delete(Guid Id);

        #endregion

        #region ExtraProperty
        [Get("/api/app/keHoachTongNguon/searchData")]
        Task<List<KeHoachTongNguonDto>> GetSearchData(int nam, string loaikehoach, string trangthai);

        [Put("/api/app/KeHoachTongNguonDieuChinh/{id}")]
        Task DeleteKeHoachVonDieuChinh(Guid id);
        #endregion
    }
}