using System;
using Refit;
using System.Collections.Generic;
using System.Threading.Tasks;
using xdcb.QuanLyVon.KeHoachTongNguonChiTiet.Dtos;

namespace xdcb.FormServices.SDK
{
	/// <summary>
	/// Generated ISDK for Table : KeHoachTongNguonChiTiet.
	/// </summary>
	public interface IKeHoachTongNguonChiTietsApi
	{
		#region Generated By Column

		[Get("/api/app/KeHoachTongNguonChiTiet")]
		Task<List<KeHoachTongNguonChiTietDto>> GetListAsync();

		[Post("/api/app/KeHoachTongNguonChiTiet")]
		Task<KeHoachTongNguonChiTietDto> Create([Body] CreateUpdateKeHoachTongNguonChiTietDto info);

		[Get("/api/app/KeHoachTongNguonChiTiet/{Id}")]
		Task<KeHoachTongNguonChiTietDto> GetAsync(Guid Id);

		[Put("/api/app/KeHoachTongNguonChiTiet/{Id}")]
		Task<KeHoachTongNguonChiTietDto> Update(Guid Id, [Body] CreateUpdateKeHoachTongNguonChiTietDto info);

		[Delete("/api/app/KeHoachTongNguonChiTiet/{Id}")]
		Task Delete(Guid Id);

		[Get("/api/app/keHoachTongNguon/{id}/keHoachTongNguonChiTiet")]
		Task<List<KeHoachTongNguonChiTietDto>> GetListByKeHoachTongNguonIdAsync(Guid id);

		[Delete("/api/app/keHoachTongNguon/{id}/keHoachTongNguonChiTiet")]
		Task DeleteByKeHoachTongNguonId(Guid id);

		[Get("/api/app/nguonVon/{id}/keHoachTongNguonChiTiet")]
		Task<List<KeHoachTongNguonChiTietDto>> GetListByNguonVonIdAsync(Guid id);

		[Delete("/api/app/nguonVon/{id}/keHoachTongNguonChiTiet")]
		Task DeleteByNguonVonId(Guid id);

		[Get("/api/app/nguonVonCha/{id}/keHoachTongNguonChiTiet")]
		Task<List<KeHoachTongNguonChiTietDto>> GetListByNguonVonChaIdAsync(Guid id);

		[Delete("/api/app/nguonVonCha/{id}/keHoachTongNguonChiTiet")]
		Task DeleteByNguonVonChaId(Guid id);

		#endregion

		#region Extraproperty

		[Put("/api/app/keHoachTongNguonDieuChinhChiTiet/{id}")]
		Task DeleteKeHoachVonDieuChinhById(Guid id);
		#endregion
	}
}