using System;
using Refit;
using System.Collections.Generic;
using System.Threading.Tasks;
using xdcb.QuanLyVon.NhuCauKeHoachVonChiTiet.Dtos;

namespace xdcb.FormServices.SDK
{
    /// <summary>
    /// Generated ISDK for Table : NhuCauKeHoachVonChiTiet.
    /// </summary>
    public interface INhuCauKeHoachVonChiTietsApi
    {
        #region Generated By Column

        [Get("/api/app/NhuCauKeHoachVonChiTiet")]
        Task<List<NhuCauKeHoachVonChiTietDto>> GetListAsync();

        [Post("/api/app/NhuCauKeHoachVonChiTiet")]
        Task<NhuCauKeHoachVonChiTietDto> Create([Body] CreateUpdateNhuCauKeHoachVonChiTietDto info);

        [Get("/api/app/NhuCauKeHoachVonChiTiet/{Id}")]
        Task<NhuCauKeHoachVonChiTietDto> GetAsync(Guid Id);

        [Put("/api/app/NhuCauKeHoachVonChiTiet/{Id}")]
        Task<NhuCauKeHoachVonChiTietDto> Update(Guid Id, [Body] CreateUpdateNhuCauKeHoachVonChiTietDto info);

        [Delete("/api/app/NhuCauKeHoachVonChiTiet/{Id}")]
        Task Delete(Guid Id);

        [Get("/api/app/nhuCauKeHoachVon/{id}/nhuCauKeHoachVonChiTiet")]
        Task<List<NhuCauKeHoachVonChiTietDto>> GetListByNhuCauKeHoachVonIDAsync(Guid id);

        [Delete("/api/app/nhuCauKeHoachVon/{id}/nhuCauKeHoachVonChiTiet")]
        Task DeleteByNhuCauKeHoachVonID(Guid id);

        [Get("/api/app/congTrinh/{id}/nhuCauKeHoachVonChiTiet")]
        Task<List<NhuCauKeHoachVonChiTietDto>> GetListByCongTrinhIDAsync(Guid id);

        [Delete("/api/app/congTrinh/{id}/nhuCauKeHoachVonChiTiet")]
        Task DeleteByCongTrinhID(Guid id);

        #endregion

        #region Property
        [Get("/api/app/nhuCauKeHoachVonChiTiet/dataByNhuCauVonIDAndCongTrinh")]
        Task<List<NhuCauKeHoachVonChiTietDto>> GetListDataByNhuCauVonIDAndCongTrinh(List<Guid> listnhuCauVonID, Guid congtrinhID);

        [Get("/api/app/nhuCauKeHoachVonChiTiet/dataSumValueByNhuCauVonID")]
        Task<NhuCauKeHoachVonChiTietDto> GetDataSumValueByNhuCauVonID(Guid nhuCauVonID);
        #endregion
    }
}