using System;
using System.ComponentModel.DataAnnotations;

namespace xdcb.QuanLyVon.KeHoachVonNQChiTiet.Dtos
{
	/// <summary>
	/// Generated CreateUpdateDto for Table : KeHoachVonNQChiTiet.
	/// </summary>
	public class CreateUpdateKeHoachVonNQChiTietDto
	{
		#region Generated By Column

		//[Required]
		public Guid KeHoachVonNQId { get; set; }

		//[Required]
		public Guid NghiQuyetId { get; set; }

		//[Required]
		public Guid CongTrinhId { get; set; }

		//[Required]
		public decimal LuyKeVonTongCong { get; set; }

		//[Required]
		public decimal LuyKeVonNamTruoc { get; set; }

		//[Required]
		public decimal KeHoachVonDauNam { get; set; }

		//[Required]
		public decimal KeHoachVonDauNamDuocDuyet { get; set; }

		//[Required]
		public decimal DieuChinhTang { get; set; }

		//[Required]
		public decimal DieuChinhGiam { get; set; }

		//[Required]
		public decimal KeHoachVonDieuChinh { get; set; }

		//[Required]
		public decimal KeHoachVonDieuChinhDuocDuyet { get; set; }

		//[StringLength(1073741823)]
		public string GhiChuSoDauNam { get; set; }

		//[StringLength(1073741823)]
		public string GhiChuUyBanDauNam { get; set; }

		//[StringLength(1073741823)]
		public string GhiChuSoDieuChinh { get; set; }

		//[StringLength(1073741823)]
		public string GhiChuUyBanDieuChinh { get; set; }

		//[StringLength(1073741823)]
		public string StringKeHoachVonDauNam { get; set; }

		//[StringLength(1073741823)]
		public string StringKeHoachVonDauNamDuocDuyet { get; set; }

		//[StringLength(1073741823)]
		public string StringDieuChinhTang { get; set; }

		//[StringLength(1073741823)]
		public string StringDieuChinhGiam { get; set; }

		//[StringLength(1073741823)]
		public string StringKeHoachVonDieuChinh { get; set; }

		//[StringLength(1073741823)]
		public string StringKeHoachVonDieuChinhDuocDuyet { get; set; }

		//[Required]
		public bool IsSelectDieuChinh { get; set; }

		//[Required]
		public bool IsDeleteDieuChinh { get; set; }

		#endregion
	}
}