using System;
using System.Collections.Generic;
using Volo.Abp.Application.Dtos;

namespace xdcb.QuanLyVon.KeHoachVonNQChiTiet.Dtos
{
    /// <summary>
    /// Generated Contracts Dto for Table : KeHoachVonNQChiTiet.
    /// </summary>
    public class KeHoachVonNQChiTietDto : FullAuditedEntityDto<Guid>
    {
        #region Generated By Column

        public Guid KeHoachVonNQId { get; set; }

        public Guid NghiQuyetId { get; set; }

        public Guid CongTrinhId { get; set; }

        public decimal LuyKeVonTongCong { get; set; }

        public decimal LuyKeVonNamTruoc { get; set; }

        public decimal KeHoachVonDauNam { get; set; }

        public decimal KeHoachVonDauNamDuocDuyet { get; set; }

        public decimal DieuChinhTang { get; set; }

        public decimal DieuChinhGiam { get; set; }

        public decimal KeHoachVonDieuChinh { get; set; }

        public decimal KeHoachVonDieuChinhDuocDuyet { get; set; }

        public string GhiChuSoDauNam { get; set; }

        public string GhiChuUyBanDauNam { get; set; }

        public string GhiChuSoDieuChinh { get; set; }

        public string GhiChuUyBanDieuChinh { get; set; }

        public string StringKeHoachVonDauNam { get; set; }

        public string StringKeHoachVonDauNamDuocDuyet { get; set; }

        public string StringDieuChinhTang { get; set; }

        public string StringDieuChinhGiam { get; set; }

        public string StringKeHoachVonDieuChinh { get; set; }

        public string StringKeHoachVonDieuChinhDuocDuyet { get; set; }

        public bool IsSelectDieuChinh { get; set; }

        public bool IsDeleteDieuChinh { get; set; }

        #endregion

        #region Extra Property
        public string TenDanhMuc { get; set; }
        public string TenChuDauTu { get; set; }
        public decimal TongVonDeAn { get; set; }
        public decimal VonDeAn { get; set; } 
        public Dictionary<string, decimal> Value { get; set; }
        public Guid KeHoachVonId { get; set; }
        public Guid ParentId { get; set; }
        public int OrderIndex { get; set; }
        public string STT { get; set; }
        public string TenLoaiCongTrinh { get; set; }
        public Guid LoaiCongTrinhID { get; set; }
        public bool IsBold { get; set; }
        #endregion
    }
}