using System;
using System.ComponentModel.DataAnnotations;

namespace xdcb.QuanLyVon.NhuCauKeHoachVon.Dtos
{
	/// <summary>
	/// Generated CreateUpdateDto for Table : NhuCauKeHoachVon.
	/// </summary>
	public class CreateUpdateNhuCauKeHoachVonDto
	{
		#region Generated By Column

		//[Required]
		public int TuNam { get; set; }

		//[Required]
		public int DenNam { get; set; }

		//[Required]
		//[StringLength(1073741823)]
		public string GiaiDoanNam { get; set; }

		//[Required]
		public Guid ChuDauTuID { get; set; }

		//[StringLength(255)]
		public string TenKeHoach { get; set; }

		//[StringLength(255)]
		public string TrangThaiDauNam { get; set; }

		//[StringLength(255)]
		public string TrangThaiDieuChinh { get; set; }

		//[Required]
		public decimal TongNhuCauVonDauNam { get; set; }

		//[Required]
		public decimal TongNhuCauVonDieuChinh { get; set; }
		public DateTime? ThoiGianGuiBaoCaoDauNam { get; set; }
		public DateTime? ThoiGianGuiBaoCaoDieuChinh { get; set; }

		#endregion
	}
}