using System;
using Volo.Abp.Application.Dtos;

namespace xdcb.QuanLyVon.NhuCauKeHoachVon.Dtos
{
	/// <summary>
	/// Generated Contracts Dto for Table : NhuCauKeHoachVon.
	/// </summary>
	public class NhuCauKeHoachVonDto : FullAuditedEntityDto<Guid>
	{
		#region Generated By Column

		public int TuNam { get; set; }

		public int DenNam { get; set; }

		public string GiaiDoanNam { get; set; }

		public Guid ChuDauTuID { get; set; }

		public string TenKeHoach { get; set; }

		public string TrangThaiDauNam { get; set; }

		public string TrangThaiDieuChinh { get; set; }

		public decimal TongNhuCauVonDauNam { get; set; }

		public decimal TongNhuCauVonDieuChinh { get; set; }
		public DateTime? ThoiGianGuiBaoCaoDauNam { get; set; }
		public DateTime? ThoiGianGuiBaoCaoDieuChinh { get; set; }

		#endregion

		#region Extra Property
		public string LoaiKeHoach { get; set; }
		public string strNotification { get; set; }
		public int OrderIndex { get; set; }
		public Guid IDNhuCauKeHoachVonLuyKe { get; set; }
		public int STT { get; set; }
		public int CountChuDauTu { get; set; }
		public decimal TongNhuCauVon { get; set; }
		public string TrangThai { get; set; }
		public Guid CongTrinhID { get; set; }
		#endregion
	}
}