using System;
using Refit;
using System.Collections.Generic;
using System.Threading.Tasks;
using xdcb.FileService.DocumentStoreDtos;

namespace xdcb.FormServices.SDK
{
    /// <summary>
    /// Generated ISDK for Table : DocumentStore.
    /// </summary>
    public interface IDocumentStoresApi
	{
		#region Generated By Column

		[Get("/api/app/DocumentStore")]
		Task<List<DocumentStoreDto>> GetListAsync();

		[Post("/api/app/DocumentStore")]
		Task<DocumentStoreDto> Create([Body] CreateUpdateDocumentStoreDto info);

		[Get("/api/app/DocumentStore/{Id}")]
		Task<DocumentStoreDto> GetAsync(Guid Id);

		[Put("/api/app/DocumentStore/{Id}")]
		Task<DocumentStoreDto> Update(Guid Id, [Body] CreateUpdateDocumentStoreDto info);

		[Delete("/api/app/DocumentStore/{Id}")]
		Task Delete(Guid Id);

		#endregion
	}
}