using System;

namespace xdcb.QuanLyVon.GiaiNganChiTiet.Dtos
{
	/// <summary>
	/// Generated CreateUpdateDto for Table : GiaiNganChiTiet.
	/// </summary>
	public class CreateUpdateGiaiNganChiTietDto
	{
		#region Generated By Column

		public Guid GiaiNganId { get; set; }

		public Guid LoaiKhoanId { get; set; }

		public Guid LoaiCongTrinhId { get; set; }

		public Guid CongTrinhId { get; set; }

		public Guid KeHoachVonNSTChiTietId { get; set; }

		public Guid KeHoachVonNSTWChiTietId { get; set; }

		public decimal LuyKeVonNamNayNST { get; set; }

		public decimal LuyKeGiaiNganNamNayNST { get; set; }

		public decimal KeHoachVonNamTruocKeoDaiNST { get; set; }

		public decimal KeHoachVonNamNayNST { get; set; }

		public decimal KhoiLuongThucHienNamNayNST { get; set; }

		public decimal GiaiNganNamNayNST { get; set; }

		public decimal GiaiNganNamTruocKeoDaiNST { get; set; }

		public string GhiChuNST { get; set; }

		public string GhiChuChuyenVienNST { get; set; }

		public bool IsSelectNST { get; set; }

		public decimal LuyKeVonNamNayNSTW { get; set; }

		public decimal LuyKeGiaiNganNamNayNSTW { get; set; }

		public decimal KeHoachVonNamTruocKeoDaiNSTW { get; set; }

		public decimal KeHoachVonNamNayNSTW { get; set; }

		public decimal KhoiLuongThucHienNamNayNSTW { get; set; }

		public decimal GiaiNganNamNayNSTW { get; set; }

		public decimal GiaiNganNamTruocKeoDaiNSTW { get; set; }

		public string GhiChuNSTW { get; set; }

		public string GhiChuChuyenVienNSTW { get; set; }

		public bool IsSelectNSTW { get; set; }

		public decimal LuyKeVonNamNayODA { get; set; }

		public decimal LuyKeGiaiNganNamNayODA { get; set; }

		public decimal KeHoachVonNamTruocKeoDaiODA { get; set; }

		public decimal KeHoachVonNamNayODA { get; set; }

		public decimal KhoiLuongThucHienNamNayODA { get; set; }

		public decimal GiaiNganNamNayODA { get; set; }

		public decimal GiaiNganNamTruocKeoDaiODA { get; set; }

		public string GhiChuODA { get; set; }

		public string GhiChuChuyenVienODA { get; set; }

		public bool IsSelectODA { get; set; }

		public bool IsSelectDieuChinh { get; set; }

		public bool IsDeleteDieuChinh { get; set; }
		#endregion
	}
}