using System;
using System.Collections.Generic;
using Volo.Abp.Application.Dtos;

namespace xdcb.Common.DanhMuc.CongTrinhDtos
{
    public class CongTrinhDto : FullAuditedEntityDto<Guid>
    {
        #region Generated By Column

        public Guid? ChuDauTuId { get; set; }

        public string MaCongTrinh { get; set; }

        public string TenCongTrinh { get; set; }

        public Guid? NhomCongTrinhId { get; set; }

        public string MaSoDuAn { get; set; }

        public Guid? LoaiKhoanId { get; set; }

        public Guid? CTMTQuocGiaId { get; set; }

        public Guid? LoaiCongTrinhId { get; set; }

        public double? DienTich { get; set; }

        public DateTime? ThoiGianThucHienTuNgay { get; set; }

        public DateTime? ThoiGianThucHienDenNgay { get; set; }

        public string SoQuyetDinhDauTu { get; set; }

        public DateTime? NgayQuyetDinhDauTu { get; set; }

        public decimal? TongMucDauTu { get; set; }

        public decimal? NST { get; set; }

        public decimal? NSTW { get; set; }

        public decimal? ODA { get; set; }

        #endregion

        #region Extra Property
        public List<DiaDiemXayDungDto> DiaDiemXayDungs { get; set; }
        public string TenChuDauTu { get; set; }
        public string TenNhomCongTrinh { get; set; }
        public string MaLoaiKhoan { get; set; }
        public string MaChuong { get; set; }
        public string MaCTMTQG { get; set; }
        public string TenLoaiCongTrinh { get; set; }
        public bool Selected { get; set; }
        public string TenLoaiKhoan { get; set; }

        public int? TuNam { get; set; }

        public int? DenNam { get; set; }

        public int STT { get; set; }
        #endregion
    }
}