using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace xdcb.Common.DanhMuc.CongTrinhDtos
{
	/// <summary>
	/// Generated CreateUpdateDto for Table : CongTrinh.
	/// </summary>
	public class CreateUpdateCongTrinhDto
	{
		#region Generated By Column

		public Guid? ChuDauTuId { get; set; }

		public string MaCongTrinh { get; set; }

		[Required(ErrorMessage = Messages.MSG_Requied)]
		[StringLength(500)]
		[System.ComponentModel.DisplayName(ViewTextConsts.CongTrinh.TenCongTrinh)]
		[Display(Prompt = ViewTextConsts.PlaceholderCongTrinh.TenCongTrinh)]
		public string TenCongTrinh { get; set; }
		
		[System.ComponentModel.DisplayName(ViewTextConsts.CongTrinh.NhomCongTrinh)]
		[Display(Prompt = ViewTextConsts.PlaceholderCongTrinh.NhomCongTrinh)]
		public Guid? NhomCongTrinhId { get; set; }

		[System.ComponentModel.DisplayName(ViewTextConsts.CongTrinh.MaSoDuAn)]
		[Display(Prompt = ViewTextConsts.PlaceholderCongTrinh.MaSoDuAn)]
		public string MaSoDuAn { get; set; }
		[System.ComponentModel.DisplayName(ViewTextConsts.CongTrinh.MaLoaiKhoan)]
		[Display(Prompt = ViewTextConsts.PlaceholderCongTrinh.MaLoaiKhoan)]
		public Guid? LoaiKhoanId { get; set; }
		[System.ComponentModel.DisplayName(ViewTextConsts.CongTrinh.MaCTMTQG)]
		[Display(Prompt = ViewTextConsts.PlaceholderCongTrinh.MaCTMTQG)]
		public Guid? CTMTQuocGiaId { get; set; }
		[System.ComponentModel.DisplayName(ViewTextConsts.CongTrinh.LoaiCongTrinh)]
		[Display(Prompt = ViewTextConsts.PlaceholderCongTrinh.LoaiCongTrinh)]
		public Guid? LoaiCongTrinhId { get; set; }
		[System.ComponentModel.DisplayName(ViewTextConsts.CongTrinh.DienTich)]
		[Display(Prompt = ViewTextConsts.PlaceholderCongTrinh.DienTich)]
		public double? DienTich { get; set; }

		[System.ComponentModel.DisplayName(ViewTextConsts.CongTrinh.TuNam)]
		public DateTime? ThoiGianThucHienTuNgay { get; set; }

		[System.ComponentModel.DisplayName(ViewTextConsts.CongTrinh.DenNam)]
		public DateTime? ThoiGianThucHienDenNgay { get; set; }

		[StringLength(500)]
		[System.ComponentModel.DisplayName(ViewTextConsts.CongTrinh.SoQDDT)]
		[Display(Prompt = ViewTextConsts.PlaceholderCongTrinh.SoQDDT)]
		public string SoQuyetDinhDauTu { get; set; }

		[System.ComponentModel.DisplayName(ViewTextConsts.CongTrinh.NgayQuyetDinh)]
		public DateTime? NgayQuyetDinhDauTu { get; set; }
		[System.ComponentModel.DisplayName(ViewTextConsts.CongTrinh.TongMucDauTu)]
		[Display(Prompt = ViewTextConsts.PlaceholderCongTrinh.NhapTongMucDauTu)]
		[DisplayFormat(DataFormatString = "{0:#.#}", ApplyFormatInEditMode = true)]
		public decimal? TongMucDauTu { get; set; }

		[System.ComponentModel.DisplayName(ViewTextConsts.CongTrinh.NST)]
		[Display(Prompt = ViewTextConsts.PlaceholderCongTrinh.NST)]
		[DisplayFormat(DataFormatString = "{0:#.#}", ApplyFormatInEditMode = true)]
		public decimal? NST { get; set; }

		[System.ComponentModel.DisplayName(ViewTextConsts.CongTrinh.NSTW)]
		[Display(Prompt = ViewTextConsts.PlaceholderCongTrinh.NSTW)]
		[DisplayFormat(DataFormatString = "{0:#.#}", ApplyFormatInEditMode = true)]
		public decimal? NSTW { get; set; }

		[System.ComponentModel.DisplayName(ViewTextConsts.CongTrinh.ODA)]
		[Display(Prompt = ViewTextConsts.PlaceholderCongTrinh.ODA)]
		[DisplayFormat(DataFormatString = "{0:#.#}", ApplyFormatInEditMode = true)]
		public decimal? ODA { get; set; }

		public List<DiaDiemXayDungDto> DiaDiemXayDungs { get; set; }

		#endregion
	}
}