using System;
namespace xdcb.QuanLyVon.GiaiNgans
{
    /// <summary>
    /// Generated Domain for Table : KeHoachTongNguon.
    /// </summary>
    public class GiaiNgan : BaseEntity
    {
        #region Generated By Column

        public int Nam { get; set; }
        public int QuyThang { get; set; }
        public Guid ChuDauTuId { get; set; }
        public bool IsKeHoachKeoDai { get; set; }
        public string TenKeHoach { get; set; }
        public string TrangThai { get; set; }
        public decimal TongGiaiNgan { get; set; }
        public DateTime? NgayGui { get; set; }
        #endregion
    }
}