using System;
using Volo.Abp.Domain.Entities.Auditing;

namespace xdcb.QuanLyVon.KeHoachTongNguons
{
    /// <summary>
    /// Generated Domain for Table : KeHoachTongNguon.
    /// </summary>
    public class KeHoachTongNguon : BaseEntity
    {
        #region Generated By Column

        public int Nam { get; set; }

        public DateTime? NgayQuyetDinhDauNam { get; set; }

        public DateTime? NgayQuyetDinhDieuChinh { get; set; }

        public string SoQuyetDinhDauNam { get; set; }

        public string SoQuyetDinhDieuChinh { get; set; }

        public decimal KeHoachDauNam { get; set; }

        public decimal KeHoachDauNamDuocDuyet { get; set; }

        public decimal KeHoachSauBoSung { get; set; }

        public decimal KeHoachSauBoSungDuocDuyet { get; set; }

        public string TrangThaiDauNam { get; set; }

        public string TrangThaiDieuChinh { get; set; }

        public string DinhKemFileDauNam { get; set; }

        public string DinhKemFileDieuChinh { get; set; }

        public string GhiChuDauNam { get; set; }

        public string GhiChuDieuChinh { get; set; }
        #endregion
    }
}