using System;
using System.Collections.Generic;
using System.Text;

namespace xdcb.QuanLyVon.KeHoachVonNSTChiTiets
{
    public class KeHoachVonNSTChiTiet: BaseEntity
    {
        #region Generated By Column
        public Guid KeHoachVonNSTId { get; set; }

        public Guid CongTrinhId { get; set; }

        public Guid? LoaiKhoanId { get; set; }

        public decimal LuyKeVonTongCong { get; set; }

        public decimal LuyKeVonNamTruoc { get; set; }

        public decimal KeHoachVonDauNam { get; set; }

        public decimal KeHoachVonDauNamDuocDuyet { get; set; }

        public decimal DieuChinhTang { get; set; }

        public decimal DieuChinhGiam { get; set; }

        public decimal KeHoachVonDieuChinh { get; set; }

        public decimal KeHoachVonDieuChinhDuocDuyet { get; set; }

        public decimal NhuCauKeHoachVonDauNam { get; set; }
        public decimal NhuCauKeHoachVonDieuChinh { get; set; }

        public Guid NhuCauKeHoachVonChiTietDauNamId { get; set; }
        public Guid NhuCauKeHoachVonChiTietDieuChinhId { get; set; }
        public string GhiChuSoDauNam { get; set; }

        public string GhiChuUyBanDauNam { get; set; }

        public string GhiChuSoDieuChinh { get; set; }

        public string GhiChuUyBanDieuChinh { get; set; }

        public string StringKeHoachVonDauNam { get; set; }

        public string StringKeHoachVonDauNamDuocDuyet { get; set; }

        public string StringDieuChinhTang { get; set; }

        public string StringDieuChinhGiam { get; set; }

        public string StringKeHoachVonDieuChinh { get; set; }

        public string StringKeHoachVonDieuChinhDuocDuyet { get; set; }

        public bool IsSelectDieuChinh { get; set; }

        public bool IsDeleteDieuChinh { get; set; }

        #endregion
    }
}
