using System;

namespace xdcb.QuanLyVon.KeHoachVonNSTWChiTiets
{
    /// <summary>
    /// Generated Domain for Table : KeHoachTongNguon.
    /// </summary>
    public class KeHoachVonNSTWChiTiet : BaseEntity
    {
        #region Generated By Column
        public Guid KeHoachVonNSTWId { get; set; }

        public Guid LoaiKhoanId { get; set; }

        public Guid CongTrinhId { get; set; }

        public Guid NhuCauKeHoachVonChiTietDauNamId { get; set; }

        public Guid NhuCauKeHoachVonChiTietDieuChinhId { get; set; }

        public decimal LuyKeVonTongCong { get; set; }

        public decimal LuyKeVonNamTruoc { get; set; }

        public decimal NhuCauKeHoachVonDauNam { get; set; }

        public decimal NhuCauKeHoachVonDieuChinh { get; set; }

        public decimal KeHoachVonDauNam { get; set; }

        public decimal KeHoachVonDauNamDuocDuyet { get; set; }

        public decimal DieuChinhTang { get; set; }

        public decimal DieuChinhGiam { get; set; }

        public decimal KeHoachVonDieuChinh { get; set; }

        public decimal KeHoachVonDieuChinhDuocDuyet { get; set; }

        public string GhiChuSoDauNam { get; set; }

        public string GhiChuUyBanDauNam { get; set; }

        public string GhiChuSoDieuChinh { get; set; }

        public string GhiChuUyBanDieuChinh { get; set; }

        public string StringKeHoachVonDauNam { get; set; }

        public string StringKeHoachVonDauNamDuocDuyet { get; set; }

        public string StringDieuChinhTang { get; set; }

        public string StringDieuChinhGiam { get; set; }

        public string StringKeHoachVonDieuChinh { get; set; }

        public string StringKeHoachVonDieuChinhDuocDuyet { get; set; }

        public bool IsSelectDieuChinh { get; set; }

        public bool IsDeleteDieuChinh { get; set; }

        #endregion
    }
}