using System;
using Volo.Abp.Domain.Entities.Auditing;

namespace xdcb.QuanLyVon.NhuCauKeHoachVons
{
    /// <summary>
    /// Generated Domain for Table : KeHoachTongNguon.
    /// </summary>
    public class NhuCauKeHoachVon : BaseEntity
    {
        #region Generated By Column
        public int TuNam { get; set; }
        public int DenNam { get; set; }
        public string GiaiDoanNam { get; set; }
        public Guid ChuDauTuID { get; set; }
        public string TenKeHoach { get; set; }
        public string TrangThaiDauNam { get; set; }
        public string TrangThaiDieuChinh { get; set; }
        public decimal TongNhuCauVonDauNam { get; set; }
        public decimal TongNhuCauVonDieuChinh { get; set; }
        public DateTime? ThoiGianGuiBaoCaoDauNam { get; set; }
        public DateTime? ThoiGianGuiBaoCaoDieuChinh { get; set; }
        #endregion
    }
}