using System;
using Volo.Abp.Domain.Entities;

namespace xdcb.QuanLyVon.vKeHoachVons
{
    public class vKeHoachVon : Entity<Guid>
    {
        #region Generated By Column
        public Guid? KeHoachVonNSTChiTietId { get; set; }
        public Guid? KeHoachVonNSTWChiTietId { get; set; }
        public Guid? KeHoachVonODAChiTietId { get; set; }
        public int Nam { get; set; }
        public string LoaiKeHoach { get; set; }
        public Guid CongTrinhId { get; set; }
        public string MaCongTrinh { get; set; }
        public string TenCongTrinh { get; set; }
        public Guid ChuDauTuId { get; set; }
        public string TenChuDauTu { get; set; }
        public string SoQuyetDinhDauTu { get; set; }
        public DateTime? NgayQuyetDinhDauTu { get; set; }
        public decimal MucDauTuNST { get; set; }
        public decimal MucDauTuNSTW { get; set; }
        public decimal MucDauTuODA { get; set; }
        public decimal TongMucDauTu { get; set; }
        public decimal KeHoachVon { get; set; }
        #endregion
    }
}
