using System;
using Volo.Abp.Domain.Entities.Auditing;

namespace xdcb.FormServices
{
    /// <summary>
    /// Generated BaseEntity
    /// </summary>
    public abstract class BaseEntity : FullAuditedAggregateRoot<Guid>
    {
        #region Generated By Column
        public int OrderIndex { get; set; }
        public Guid TenantId { get; set; }
        #endregion
    }
}