using Volo.Abp.Domain.Entities.Auditing;

namespace xdcb.FormServices.ConfigColumns
{
    /// <summary>
    /// Generated Entity for Table : ConfigColumns.
    /// </summary>
    public class ConfigColumn : AuditedAggregateRoot<int>
    {
        #region Generated By Column

        public string Status { get; set; }

        public string ConfigColumnName { get; set; }

        public string ConfigColumnCaption { get; set; }

        public int? ConfigColumnVisibleIndex { get; set; }

        public string ConfigColumnDataType { get; set; }

        public int? ConfigColumnLength { get; set; }

        public bool? ConfigColumnAllowEdit { get; set; }

        public bool? ConfigColumnIsVisible { get; set; }

        public string ConfigColumnDisplayFormat { get; set; }

        public string ConfigColumnTableName { get; set; }

        public string ConfigColumnFunctionCode { get; set; }

        public string ConfigColumnDataSource { get; set; }

        public string ConfigColumnDisplayMember { get; set; }

        public string ConfigColumnValueMember { get; set; }

        public string ConfigColumnFilter { get; set; }

        public int? ConfigColumnWidth { get; set; }

        #endregion Generated By Column
    }
}