using System;
using Volo.Abp.Domain.Entities.Auditing;

namespace xdcb.FormServices.Modules
{
    /// <summary>
    /// Generated Entity for Table : ConfigColumns.
    /// </summary>
    public class Module : BaseEntity
    {
        #region Generated By Column
        public Guid ModuleGroupId { get; set; }
        public string ModuleNo { get; set; }
        public string ModuleName { get; set; }
        public bool IsScreenDetail { get; set; }
        public bool IsScreenSearch { get; set; }
        #endregion Generated By Column
    }
}