using System;
using Volo.Abp.Domain.Entities.Auditing;

namespace xdcb.FormServices.ModuleGroups
{
    /// <summary>
    /// Generated Entity for Table : ConfigColumns.
    /// </summary>
    public class ModuleGroup : BaseEntity
    {
        #region Generated By Column
        public string ModuleGroupNo { get; set; }
        public string ModuleGroupName { get; set; }
        #endregion Generated By Column
    }
}