using System;
using System.ComponentModel.DataAnnotations;

namespace xdcb.QuanLyVon.KeHoachTongNguon.Dtos
{
	/// <summary>
	/// Generated CreateUpdateDto for Table : KeHoachTongNguon.
	/// </summary>
	public class CreateUpdateKeHoachTongNguonDto
	{
		#region Generated By Column

		//[Required]
		public int Nam { get; set; }

		//[StringLength(27)]
		public DateTime? NgayQuyetDinhDauNam { get; set; }

		//[StringLength(27)]
		public DateTime? NgayQuyetDinhDieuChinh { get; set; }

		//[StringLength(255)]
		public string SoQuyetDinhDauNam { get; set; }

		//[StringLength(255)]
		public string SoQuyetDinhDieuChinh { get; set; }

		//[Required]
		public decimal KeHoachDauNam { get; set; }

		//[Required]
		public decimal KeHoachDauNamDuocDuyet { get; set; }

		//[Required]
		public decimal KeHoachSauBoSung { get; set; }

		//[Required]
		public decimal KeHoachSauBoSungDuocDuyet { get; set; }

		//[Required]
		//[StringLength(255)]
		public string TrangThaiDauNam { get; set; }

		//[Required]
		//[StringLength(255)]
		public string TrangThaiDieuChinh { get; set; }

		//[StringLength(500)]
		public string DinhKemFileDauNam { get; set; }

		//[StringLength(500)]
		public string DinhKemFileDieuChinh { get; set; }

		//[StringLength(1073741823)]
		public string GhiChuDauNam { get; set; }

		//[StringLength(1073741823)]
		public string GhiChuDieuChinh { get; set; }

		#endregion
	}
}