using System;
using Volo.Abp.Application.Dtos;

namespace xdcb.QuanLyVon.KeHoachTongNguon.Dtos
{
    /// <summary>
    /// Generated Contracts Dto for Table : KeHoachTongNguon.
    /// </summary>
    public class KeHoachTongNguonDto : FullAuditedEntityDto<Guid>
    {
        #region Generated By Column

        public int Nam { get; set; }

        public DateTime NgayQuyetDinhDauNam { get; set; }

        public DateTime NgayQuyetDinhDieuChinh { get; set; }

        public string SoQuyetDinhDauNam { get; set; }

        public string SoQuyetDinhDieuChinh { get; set; }

        public decimal KeHoachDauNam { get; set; }

        public decimal KeHoachDauNamDuocDuyet { get; set; }

        public decimal KeHoachSauBoSung { get; set; }

        public decimal KeHoachSauBoSungDuocDuyet { get; set; }

        public string TrangThaiDauNam { get; set; }

        public string TrangThaiDieuChinh { get; set; }

        public string DinhKemFileDauNam { get; set; }

        public string DinhKemFileDieuChinh { get; set; }

        public string GhiChuDauNam { get; set; }

        public string GhiChuDieuChinh { get; set; }

        #endregion

        #region Extraproperty
        public string LoaiKeHoach { get; set; }
        public string TrangThai { get; set; }
        public string GhiChu { get; set; }
        public DateTime NgayQuyetDinh { get; set; }
        public string SoQuyetDinh { get; set; }
        public string DinhKemFile { get; set; }
        public int NamOld { get; set; }
        public string NgaySoQuyetDinh { get; set; }
        #endregion
    }
}