using System;
using System.ComponentModel.DataAnnotations;

namespace xdcb.QuanLyVon.NhuCauKeHoachVonChiTiet.Dtos
{
	/// <summary>
	/// Generated CreateUpdateDto for Table : NhuCauKeHoachVonChiTiet.
	/// </summary>
	public class CreateUpdateNhuCauKeHoachVonChiTietDto
	{
		#region Generated By Column

		//[Required]
		public Guid NhuCauKeHoachVonID { get; set; }

		//[Required]
		public Guid CongTrinhID { get; set; }

		//[Required]
		public decimal LuyKeKhoiLuongNamTruocNST { get; set; }

		//[Required]
		public decimal LuyKeVonNamTruocNST { get; set; }

		//[Required]
		public decimal NhuCauVonDauNamNST { get; set; }

		//[Required]
		public decimal DieuChinhGiamNST { get; set; }

		//[Required]
		public decimal DieuChinhTangNST { get; set; }

		//[Required]
		public decimal NhuCauVonDieuChinhNST { get; set; }

		//[StringLength(1073741823)]
		public string GhiChuDauNamNST { get; set; }

		//[StringLength(1073741823)]
		public string GhiChuDieuChinhNST { get; set; }

		//[StringLength(1073741823)]
		public string GhiChuChuyenVienDauNamNST { get; set; }

		//[StringLength(1073741823)]
		public string GhiChuChuyenVienDieuChinhNST { get; set; }

		//[Required]
		public bool IsSelectNST { get; set; }

		//[Required]
		public decimal LuyKeKhoiLuongNamTruocNSTW { get; set; }

		//[Required]
		public decimal LuyKeVonNamTruocNSTW { get; set; }

		//[Required]
		public decimal NhuCauVonDauNamNSTW { get; set; }

		//[Required]
		public decimal DieuChinhGiamNSTW { get; set; }

		//[Required]
		public decimal DieuChinhTangNSTW { get; set; }

		//[Required]
		public decimal NhuCauVonDieuChinhNSTW { get; set; }

		//[StringLength(1073741823)]
		public string GhiChuDauNamNSTW { get; set; }

		//[StringLength(1073741823)]
		public string GhiChuDieuChinhNSTW { get; set; }

		//[StringLength(1073741823)]
		public string GhiChuChuyenVienDauNamNSTW { get; set; }

		//[StringLength(1073741823)]
		public string GhiChuChuyenVienDieuChinhNSTW { get; set; }

		//[Required]
		public bool IsSelectNSTW { get; set; }

		//[Required]
		public decimal LuyKeKhoiLuongNamTruocODA { get; set; }

		//[Required]
		public decimal LuyKeVonNamTruocODA { get; set; }

		//[Required]
		public decimal NhuCauVonDauNamODA { get; set; }

		//[Required]
		public decimal DieuChinhGiamODA { get; set; }

		//[Required]
		public decimal DieuChinhTangODA { get; set; }

		//[Required]
		public decimal NhuCauVonDieuChinhODA { get; set; }

		//[StringLength(1073741823)]
		public string GhiChuDauNamODA { get; set; }

		//[StringLength(1073741823)]
		public string GhiChuDieuChinhODA { get; set; }

		//[StringLength(1073741823)]
		public string GhiChuChuyenVienDauNamODA { get; set; }

		//[StringLength(1073741823)]
		public string GhiChuChuyenVienDieuChinhODA { get; set; }

		//[Required]
		public bool IsSelectODA { get; set; }

		//[Required]
		public bool IsSelect { get; set; }

		//[Required]
		public bool IsDeleteDieuChinh { get; set; }

		//[Required]
		public bool IsSelectDieuChinh { get; set; }

		#endregion
	}
}