using System;
using Volo.Abp.Application.Dtos;

namespace xdcb.QuanLyVon.NhuCauKeHoachVonChiTiet.Dtos
{
    /// <summary>
    /// Generated Contracts Dto for Table : NhuCauKeHoachVonChiTiet.
    /// </summary>
    public class NhuCauKeHoachVonChiTietDto : FullAuditedEntityDto<Guid>
    {
        #region Generated By Column

        public Guid NhuCauKeHoachVonID { get; set; }

        public Guid CongTrinhID { get; set; }

        public decimal LuyKeKhoiLuongNamTruocNST { get; set; }

        public decimal LuyKeVonNamTruocNST { get; set; }

        public decimal NhuCauVonDauNamNST { get; set; }

        public decimal DieuChinhGiamNST { get; set; }

        public decimal DieuChinhTangNST { get; set; }

        public decimal NhuCauVonDieuChinhNST { get; set; }

        public string GhiChuDauNamNST { get; set; }

        public string GhiChuDieuChinhNST { get; set; }

        public string GhiChuChuyenVienDauNamNST { get; set; }

        public string GhiChuChuyenVienDieuChinhNST { get; set; }

        public bool IsSelectNST { get; set; }

        public decimal LuyKeKhoiLuongNamTruocNSTW { get; set; }

        public decimal LuyKeVonNamTruocNSTW { get; set; }

        public decimal NhuCauVonDauNamNSTW { get; set; }

        public decimal DieuChinhGiamNSTW { get; set; }

        public decimal DieuChinhTangNSTW { get; set; }

        public decimal NhuCauVonDieuChinhNSTW { get; set; }

        public string GhiChuDauNamNSTW { get; set; }

        public string GhiChuDieuChinhNSTW { get; set; }

        public string GhiChuChuyenVienDauNamNSTW { get; set; }

        public string GhiChuChuyenVienDieuChinhNSTW { get; set; }

        public bool IsSelectNSTW { get; set; }

        public decimal LuyKeKhoiLuongNamTruocODA { get; set; }

        public decimal LuyKeVonNamTruocODA { get; set; }

        public decimal NhuCauVonDauNamODA { get; set; }

        public decimal DieuChinhGiamODA { get; set; }

        public decimal DieuChinhTangODA { get; set; }

        public decimal NhuCauVonDieuChinhODA { get; set; }

        public string GhiChuDauNamODA { get; set; }

        public string GhiChuDieuChinhODA { get; set; }

        public string GhiChuChuyenVienDauNamODA { get; set; }

        public string GhiChuChuyenVienDieuChinhODA { get; set; }

        public bool IsSelectODA { get; set; }

        public bool IsSelect { get; set; }

        public bool IsDeleteDieuChinh { get; set; }

        public bool IsSelectDieuChinh { get; set; }

        #endregion

        #region Extra Property
        public decimal LuyKeKhoiLuongNamTruocTongCong { get; set; }
        public decimal LuyKeVonNamTruocTongCong { get; set; }
        public decimal NhuCauVonDauNamTongCong { get; set; }
        public decimal DieuChinhGiamTongCong { get; set; }
        public decimal DieuChinhTangTongCong { get; set; }
        public decimal NhuCauVonDieuChinhTongCong { get; set; }
        public int OrderIndex { get; set; }
        public int STT { get; set; }
        public Guid ChuDauTuID { get; set; }
        public string TenChuDauTu { get; set; }
        public string MaSoDuAn { get; set; }
        public string MaSoChuong { get; set; }
        public string MaLoaiKhoan { get; set; }
        public string TenLoaiKhoan { get; set; }
        public Guid LoaiKhoanId { get; set; }
        public string TenNhomCongTrinh { get; set; }
        public string TenCongTrinh { get; set; }
        public string MaCongTrinh { get; set; }
        public string SoQuyetDinh { get; set; }
        public DateTime? NgayBanHanh { get; set; }
        public decimal TongMucDauTu { get; set; }
        public decimal MucDauTuNST { get; set; }
        public decimal MucDauTuNSTW { get; set; }
        public decimal MucDauTuODA { get; set; }
        public Guid LoaiCongTrinhId { get; set; }
        public string TenDanhMuc { get; set; }
        public string SoThuTu { get; set; }

        public bool IsBold { get; set; }

        public string TenLoaiCongTrinh { get; set; }
        #endregion
    }
}