using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using xdcb.QuanLyVon.KeHoachVonNQChiTiet.Dtos;

namespace xdcb.QuanLyVon.KeHoachVonNQChiTiets
{
    /// <summary>
    /// Generated AppService for Table : KeHoachVonNQChiTiet.
    /// </summary>
    public class KeHoachVonNQChiTietAppService : QuanLyVonAppServiceBase, IKeHoachVonNQChiTietAppService
    {
        #region Generated By Column

        private readonly IKeHoachVonNQChiTietRepository _iKeHoachVonNQChiTietRepository;

        public KeHoachVonNQChiTietAppService(IKeHoachVonNQChiTietRepository iKeHoachVonNQChiTietRepository)
        {
            _iKeHoachVonNQChiTietRepository = iKeHoachVonNQChiTietRepository;
        }

        public async Task<List<KeHoachVonNQChiTietDto>> GetListAsync()
        {
            var items = await _iKeHoachVonNQChiTietRepository.GetListAsync();
            if (items != null && items.Count > 0)
            {
                items = items.Where(x => x.IsDeleted == false).ToList();
            }
            return new List<KeHoachVonNQChiTietDto>(ObjectMapper.Map<List<KeHoachVonNQChiTiet>, List<KeHoachVonNQChiTietDto>>(items));
        }

        public async Task<KeHoachVonNQChiTietDto> GetAsync(Guid id)
        {
            var items = await _iKeHoachVonNQChiTietRepository.GetAsync(id);
            if (items != null && items.IsDeleted == true)
            {
                items = null;
            }
            return ObjectMapper.Map<KeHoachVonNQChiTiet, KeHoachVonNQChiTietDto>(items);
        }

        public async Task<KeHoachVonNQChiTietDto> Create(CreateUpdateKeHoachVonNQChiTietDto input)
        {
            var item = ObjectMapper.Map<CreateUpdateKeHoachVonNQChiTietDto, KeHoachVonNQChiTiet>(input);
            var data = await _iKeHoachVonNQChiTietRepository.InsertAsync(item, true);
            return ObjectMapper.Map<KeHoachVonNQChiTiet, KeHoachVonNQChiTietDto>(data);
        }

        public async Task<KeHoachVonNQChiTietDto> Update(Guid id, CreateUpdateKeHoachVonNQChiTietDto input)
        {
            var item = await _iKeHoachVonNQChiTietRepository.GetAsync(id);
            if (item != null && item.IsDeleted == false)
            {
                item.KeHoachVonNQId = input.KeHoachVonNQId;
                item.NghiQuyetId = input.NghiQuyetId;
                item.CongTrinhId = input.CongTrinhId;
                item.LuyKeVonNamTruoc = input.LuyKeVonNamTruoc;
                item.KeHoachVonDauNam = input.KeHoachVonDauNam;
                item.KeHoachVonDauNamDuocDuyet = input.KeHoachVonDauNamDuocDuyet;
                item.DieuChinhTang = input.DieuChinhTang;
                item.DieuChinhGiam = input.DieuChinhGiam;
                item.KeHoachVonDieuChinh = input.KeHoachVonDieuChinh;
                item.KeHoachVonDieuChinhDuocDuyet = input.KeHoachVonDieuChinhDuocDuyet;
                item.GhiChuSoDauNam = input.GhiChuSoDauNam;
                item.GhiChuUyBanDauNam = input.GhiChuUyBanDauNam;
                item.GhiChuSoDieuChinh = input.GhiChuSoDieuChinh;
                item.GhiChuUyBanDieuChinh = input.GhiChuUyBanDieuChinh;
                item.StringKeHoachVonDauNam = input.StringKeHoachVonDauNam;
                item.StringKeHoachVonDauNamDuocDuyet = input.StringKeHoachVonDauNamDuocDuyet;
                item.StringDieuChinhTang = input.StringDieuChinhTang;
                item.StringDieuChinhGiam = input.StringDieuChinhGiam;
                item.StringKeHoachVonDieuChinh = input.StringKeHoachVonDieuChinh;
                item.StringKeHoachVonDieuChinhDuocDuyet = input.StringKeHoachVonDieuChinhDuocDuyet;
                item.IsSelectDieuChinh = input.IsSelectDieuChinh;
                item.IsDeleteDieuChinh = input.IsDeleteDieuChinh;
                var data = await _iKeHoachVonNQChiTietRepository.UpdateAsync(item, true);
                return ObjectMapper.Map<KeHoachVonNQChiTiet, KeHoachVonNQChiTietDto>(data);
            }
            return ObjectMapper.Map<KeHoachVonNQChiTiet, KeHoachVonNQChiTietDto>(item);
        }

        public async Task Delete(Guid id)
        {
            var item = await _iKeHoachVonNQChiTietRepository.GetAsync(id);
            if (item != null && item.IsDeleted == false)
            {
                item.IsDeleted = true;
                await _iKeHoachVonNQChiTietRepository.UpdateAsync(item, true);
            }
        }

        [HttpGet]
        [Route("/api/app/keHoachVonNQ/{id}/keHoachVonNQChiTiet")]
        public async Task<List<KeHoachVonNQChiTietDto>> GetListByKeHoachVonNQIdAsync(Guid id)
        {
            var items = await _iKeHoachVonNQChiTietRepository.GetListAsync();
            if (items != null && items.Count > 0)
            {
                items = items.Where(x => x.IsDeleted == false && x.KeHoachVonNQId == id).ToList();
            }
            return new List<KeHoachVonNQChiTietDto>(ObjectMapper.Map<List<KeHoachVonNQChiTiet>, List<KeHoachVonNQChiTietDto>>(items));
        }

        [HttpDelete]
        [Route("/api/app/keHoachVonNQ/{id}/keHoachVonNQChiTiet")]
        public async Task DeleteByKeHoachVonNQId(Guid id)
        {
            var items = await _iKeHoachVonNQChiTietRepository.GetListAsync();
            if (items != null && items.Count > 0)
            {
                items = items.Where(x => x.IsDeleted == false && x.KeHoachVonNQId == id).ToList();
                items.ForEach(o =>
                {
                    o.IsDeleted = true;
                    _iKeHoachVonNQChiTietRepository.UpdateAsync(o);
                });
            }
        }
        [HttpGet]
        [Route("/api/app/nghiQuyet/{id}/keHoachVonNQChiTiet")]
        public async Task<List<KeHoachVonNQChiTietDto>> GetListByNghiQuyetIdAsync(Guid id)
        {
            var items = await _iKeHoachVonNQChiTietRepository.GetListAsync();
            if (items != null && items.Count > 0)
            {
                items = items.Where(x => x.IsDeleted == false && x.NghiQuyetId == id).ToList();
            }
            return new List<KeHoachVonNQChiTietDto>(ObjectMapper.Map<List<KeHoachVonNQChiTiet>, List<KeHoachVonNQChiTietDto>>(items));
        }

        [HttpDelete]
        [Route("/api/app/nghiQuyet/{id}/keHoachVonNQChiTiet")]
        public async Task DeleteByNghiQuyetId(Guid id)
        {
            var items = await _iKeHoachVonNQChiTietRepository.GetListAsync();
            if (items != null && items.Count > 0)
            {
                items = items.Where(x => x.IsDeleted == false && x.NghiQuyetId == id).ToList();
                items.ForEach(o =>
                {
                    o.IsDeleted = true;
                    _iKeHoachVonNQChiTietRepository.UpdateAsync(o);
                });
            }
        }
        [HttpGet]
        [Route("/api/app/congTrinh/{id}/keHoachVonNQChiTiet")]
        public async Task<List<KeHoachVonNQChiTietDto>> GetListByCongTrinhIdAsync(Guid id)
        {
            var items = await _iKeHoachVonNQChiTietRepository.GetListAsync();
            if (items != null && items.Count > 0)
            {
                items = items.Where(x => x.IsDeleted == false && x.CongTrinhId == id).ToList();
            }
            return new List<KeHoachVonNQChiTietDto>(ObjectMapper.Map<List<KeHoachVonNQChiTiet>, List<KeHoachVonNQChiTietDto>>(items));
        }

        [HttpDelete]
        [Route("/api/app/congTrinh/{id}/keHoachVonNQChiTiet")]
        public async Task DeleteByCongTrinhId(Guid id)
        {
            var items = await _iKeHoachVonNQChiTietRepository.GetListAsync();
            if (items != null && items.Count > 0)
            {
                items = items.Where(x => x.IsDeleted == false && x.CongTrinhId == id).ToList();
                items.ForEach(o =>
                {
                    o.IsDeleted = true;
                    _iKeHoachVonNQChiTietRepository.UpdateAsync(o);
                });
            }
        }
        #endregion

        #region ExtraProperty
        [HttpPut]
        [Route("/api/app/keHoachVonNQDieuChinhChiTietById/{id}")]
        public async Task DeleteKeHoachVonNQDieuChinhChiTietById(Guid id)
        {
            var item = await _iKeHoachVonNQChiTietRepository.GetAsync(id);
            if (item != null && item.IsDeleted == false)
            {
                item.DieuChinhTang = 0;
                item.DieuChinhGiam = 0;
                item.KeHoachVonDieuChinh = 0;
                item.KeHoachVonDieuChinhDuocDuyet = 0;
                item.GhiChuSoDieuChinh = string.Empty;
                item.GhiChuUyBanDieuChinh = string.Empty;
                item.IsDeleteDieuChinh = true;
                await _iKeHoachVonNQChiTietRepository.UpdateAsync(item, true);
            }
        }

        [HttpPut]
        [Route("/api/app/keHoachVonNQ/{id}keHoachVonNQDieuChinhChiTiet")]
        public async Task DeleteDataDieuChinhByKeHoachVonNQID(Guid id)
        {
            var items = await _iKeHoachVonNQChiTietRepository.GetListAsync();
            if (items != null && items.Count > 0)
            {
                items = items.Where(x => x.IsDeleted == false && x.KeHoachVonNQId == id).ToList();
                items.ForEach(o =>
                {
                    o.DieuChinhGiam = 0;
                    o.DieuChinhTang = 0;
                    o.KeHoachVonDieuChinh = 0;
                    o.KeHoachVonDieuChinhDuocDuyet = 0;
                    o.GhiChuSoDieuChinh = string.Empty;
                    o.GhiChuUyBanDieuChinh = string.Empty;
                    o.StringDieuChinhGiam = string.Empty;
                    o.StringDieuChinhTang = string.Empty;
                    o.StringKeHoachVonDieuChinh = string.Empty;
                    o.StringKeHoachVonDieuChinhDuocDuyet = string.Empty;
                    o.IsDeleteDieuChinh = true;
                    _iKeHoachVonNQChiTietRepository.UpdateAsync(o);
                });
            }
        }
        public async Task<List<KeHoachVonNQChiTietDto>> GetDataLuyKeByNam(int nam)
        {
            var items = await _iKeHoachVonNQChiTietRepository.GetDataLuyKeByNam(nam);
            return ObjectMapper.Map<List<KeHoachVonNQChiTiet>, List<KeHoachVonNQChiTietDto>>(items);
        }
        #endregion
    }
}