using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using xdcb.QuanLyVon.KeHoachVonNST.Dtos;

namespace xdcb.QuanLyVon.KeHoachVonNSTs
{
    public class KeHoachVonNSTAppService : QuanLyVonAppServiceBase, IKeHoachVonNSTAppService
    {
        #region Generated By Column

        private readonly IKeHoachVonNSTRepository _iKeHoachVonNSTRepository;

        public KeHoachVonNSTAppService(IKeHoachVonNSTRepository iKeHoachVonNSTRepository)
        {
            _iKeHoachVonNSTRepository = iKeHoachVonNSTRepository;
        }

        public async Task<List<KeHoachVonNSTDto>> GetListAsync()
        {
            var items = await _iKeHoachVonNSTRepository.GetListAsync();
            if (items != null && items.Count > 0)
            {
                items = items.Where(x => x.IsDeleted == false).ToList();
            }
            return new List<KeHoachVonNSTDto>(ObjectMapper.Map<List<KeHoachVonNST>, List<KeHoachVonNSTDto>>(items));
        }

        public async Task<KeHoachVonNSTDto> GetAsync(Guid id)
        {
            var items = await _iKeHoachVonNSTRepository.GetAsync(id);
            if (items != null && items.IsDeleted == true)
            {
                items = null;
            }
            return ObjectMapper.Map<KeHoachVonNST, KeHoachVonNSTDto>(items);
        }

        public async Task<KeHoachVonNSTDto> Create(CreateUpdateKeHoachVonNSTDto input)
        {
            var item = ObjectMapper.Map<CreateUpdateKeHoachVonNSTDto, KeHoachVonNST>(input);
            var data = await _iKeHoachVonNSTRepository.InsertAsync(item, true);
            return ObjectMapper.Map<KeHoachVonNST, KeHoachVonNSTDto>(data);
        }

        public async Task<KeHoachVonNSTDto> Update(Guid id, CreateUpdateKeHoachVonNSTDto input)
        {
            var item = await _iKeHoachVonNSTRepository.GetAsync(id);
            if (item != null && item.IsDeleted == false)
            {
                item.Nam = input.Nam;
                item.KeHoachVonDauNam = input.KeHoachVonDauNam;
                item.KeHoachVonDauNamDuocDuyet = input.KeHoachVonDauNamDuocDuyet;
                item.KeHoachVonDieuChinh = input.KeHoachVonDieuChinh;
                item.KeHoachVonDieuChinhDuocDuyet = input.KeHoachVonDieuChinhDuocDuyet;
                item.TrangThaiDauNam = input.TrangThaiDauNam;
                item.TrangThaiDieuChinh = input.TrangThaiDieuChinh;
                item.NgayBanHanhDauNam = input.NgayBanHanhDauNam;
                item.NgayBanHanhDieuChinh = input.NgayBanHanhDieuChinh;
                item.SoQuyetDinhDauNam = input.SoQuyetDinhDauNam;
                item.SoQuyetDinhDieuChinh = input.SoQuyetDinhDieuChinh;
                item.DinhKemFileDauNam = input.DinhKemFileDauNam;
                item.DinhKemFileDieuChinh = input.DinhKemFileDieuChinh;
                var data = await _iKeHoachVonNSTRepository.UpdateAsync(item, true);
                return ObjectMapper.Map<KeHoachVonNST, KeHoachVonNSTDto>(data);
            }
            return ObjectMapper.Map<KeHoachVonNST, KeHoachVonNSTDto>(item);
        }

        public async Task Delete(Guid id)
        {
            var item = await _iKeHoachVonNSTRepository.GetAsync(id);
            if (item != null && item.IsDeleted == false)
            {
                item.IsDeleted = true;
                await _iKeHoachVonNSTRepository.UpdateAsync(item, true);
            }
        }

        #endregion

        #region Property
        public async Task<List<KeHoachVonNSTDto>> GetSearchData(int nam, string loaikehoach, string trangthai)
        {
            List<KeHoachVonNSTDto> list = new List<KeHoachVonNSTDto>();

            if (string.IsNullOrWhiteSpace(loaikehoach))
            {
                loaikehoach = "";
            }
            if (string.IsNullOrWhiteSpace(trangthai))
            {
                trangthai = "";
            }
            var item = _iKeHoachVonNSTRepository.GetListAsync().GetAwaiter().GetResult().ToList();
            if (item != null && item.Count > 0)
            {

                //daunam
                item.Where(x => !string.IsNullOrWhiteSpace(x.TrangThaiDauNam)
                            && (nam == 0 || x.Nam == nam)
                ).ToList().ForEach(o =>
                {
                    var dto = ObjectMapper.Map<KeHoachVonNST, KeHoachVonNSTDto>(o);
                    dto.TrangThai = dto.TrangThaiDauNam;
                    dto.DinhKemFile = dto.DinhKemFileDauNam;
                    dto.NgayBanHanh = dto.NgayBanHanhDauNam;
                    dto.DinhKemFile = dto.DinhKemFileDauNam;
                    dto.SoQuyetDinh = dto.SoQuyetDinhDauNam;
                    dto.KeHoachVonDieuChinh = 0;
                    dto.KeHoachVonDieuChinhDuocDuyet = 0;
                    dto.LoaiKeHoach = "DAU_NAM";
                    list.Add(dto);
                });
                //dieuchinh
                item.Where(x => !string.IsNullOrWhiteSpace(x.TrangThaiDieuChinh)
                            && (nam == 0 || x.Nam == nam)
                ).ToList().ForEach(o =>
                {
                    var dto = ObjectMapper.Map<KeHoachVonNST, KeHoachVonNSTDto>(o);
                    dto.TrangThai = dto.TrangThaiDieuChinh;
                    dto.DinhKemFile = dto.DinhKemFileDieuChinh;
                    dto.NgayBanHanh = dto.NgayBanHanhDieuChinh;
                    dto.DinhKemFile = dto.DinhKemFileDieuChinh;
                    dto.SoQuyetDinh = dto.SoQuyetDinhDieuChinh;
                    dto.LoaiKeHoach = "DIEU_CHINH";
                    list.Add(dto);
                });

                list = list.Where(x => !string.IsNullOrWhiteSpace(x.LoaiKeHoach)
                                && (loaikehoach == "" || x.LoaiKeHoach == loaikehoach)
                                && (trangthai == "" || x.TrangThai == trangthai)).ToList();
            }
            return list;
        }
        [HttpPut]
        [Route("/api/app/KeHoachVonNSTDieuChinh/{id}")]
        public async Task DeleteKeHoachVonNSTDieuChinh(Guid id)
        {
            var item = await _iKeHoachVonNSTRepository.GetAsync(id);
            if (item != null && item.IsDeleted == false)
            {
                item.TrangThaiDieuChinh = string.Empty;
                item.DinhKemFileDieuChinh = string.Empty;
                item.KeHoachVonDieuChinh = 0;
                item.KeHoachVonDieuChinhDuocDuyet = 0;
                item.NgayBanHanhDieuChinh = null;
                await _iKeHoachVonNSTRepository.UpdateAsync(item, true);
            }
        }
        #endregion
    }
}
