using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using xdcb.QuanLyVon.KeHoachTongNguon.Dtos;

namespace xdcb.QuanLyVon.KeHoachTongNguons
{
    /// <summary>
    /// Generated AppService for Table : KeHoachTongNguon.
    /// </summary>
    public class KeHoachTongNguonAppService : QuanLyVonAppServiceBase, IKeHoachTongNguonAppService
    {
        #region Generated By Column

        private readonly IKeHoachTongNguonRepository _iKeHoachTongNguonRepository;

        public KeHoachTongNguonAppService(IKeHoachTongNguonRepository iKeHoachTongNguonRepository)
        {
            _iKeHoachTongNguonRepository = iKeHoachTongNguonRepository;
        }

        public async Task<List<KeHoachTongNguonDto>> GetListAsync()
        {
            var items = await _iKeHoachTongNguonRepository.GetListAsync();
            if (items != null && items.Count > 0)
            {
                items = items.Where(x => x.IsDeleted == false).ToList();
            }
            return new List<KeHoachTongNguonDto>(ObjectMapper.Map<List<KeHoachTongNguon>, List<KeHoachTongNguonDto>>(items));
        }

        public async Task<KeHoachTongNguonDto> GetAsync(Guid id)
        {
            var items = await _iKeHoachTongNguonRepository.GetAsync(id);
            if (items != null && items.IsDeleted == true)
            {
                items = null;
            }
            return ObjectMapper.Map<KeHoachTongNguon, KeHoachTongNguonDto>(items);
        }

        public async Task<KeHoachTongNguonDto> Create(CreateUpdateKeHoachTongNguonDto input)
        {
            var item = ObjectMapper.Map<CreateUpdateKeHoachTongNguonDto, KeHoachTongNguon>(input);
            var data = await _iKeHoachTongNguonRepository.InsertAsync(item, true);
            return ObjectMapper.Map<KeHoachTongNguon, KeHoachTongNguonDto>(data);
        }

        public async Task<KeHoachTongNguonDto> Update(Guid id, CreateUpdateKeHoachTongNguonDto input)
        {
            var item = await _iKeHoachTongNguonRepository.GetAsync(id);
            if (item != null && item.IsDeleted == false)
            {
                item.Nam = input.Nam;
                item.NgayQuyetDinhDauNam = input.NgayQuyetDinhDauNam;
                item.NgayQuyetDinhDieuChinh = input.NgayQuyetDinhDieuChinh;
                item.SoQuyetDinhDauNam = input.SoQuyetDinhDauNam;
                item.SoQuyetDinhDieuChinh = input.SoQuyetDinhDieuChinh;
                item.KeHoachDauNam = input.KeHoachDauNam;
                item.KeHoachDauNamDuocDuyet = input.KeHoachDauNamDuocDuyet;
                item.KeHoachSauBoSung = input.KeHoachSauBoSung;
                item.KeHoachSauBoSungDuocDuyet = input.KeHoachSauBoSungDuocDuyet;
                item.TrangThaiDauNam = input.TrangThaiDauNam;
                item.TrangThaiDieuChinh = input.TrangThaiDieuChinh;
                item.DinhKemFileDauNam = input.DinhKemFileDauNam;
                item.DinhKemFileDieuChinh = input.DinhKemFileDieuChinh;
                item.GhiChuDauNam = input.GhiChuDauNam;
                item.GhiChuDieuChinh = input.GhiChuDieuChinh;
                var data = await _iKeHoachTongNguonRepository.UpdateAsync(item, true);
                return ObjectMapper.Map<KeHoachTongNguon, KeHoachTongNguonDto>(data);
            }
            return ObjectMapper.Map<KeHoachTongNguon, KeHoachTongNguonDto>(item);
        }

        public async Task Delete(Guid id)
        {
            var item = await _iKeHoachTongNguonRepository.GetAsync(id);
            if (item != null && item.IsDeleted == false)
            {
                item.IsDeleted = true;
                await _iKeHoachTongNguonRepository.UpdateAsync(item, true);
            }
        }

        #endregion

        #region Property
        public async Task<List<KeHoachTongNguonDto>> GetSearchData(int nam, string loaikehoach, string trangthai)
        {
            List<KeHoachTongNguonDto> list = new List<KeHoachTongNguonDto>();

            if (string.IsNullOrWhiteSpace(loaikehoach))
            {
                loaikehoach = "";
            }
            if (string.IsNullOrWhiteSpace(trangthai))
            {
                trangthai = "";
            }
            var item = _iKeHoachTongNguonRepository.GetListAsync().GetAwaiter().GetResult().ToList();
            if (item != null && item.Count > 0)
            {
                //daunam
                item.Where(x => !string.IsNullOrWhiteSpace(x.TrangThaiDauNam)
                            && (nam == 0 || x.Nam == nam)
                ).ToList().ForEach(o =>
                {
                    var dto = ObjectMapper.Map<KeHoachTongNguon, KeHoachTongNguonDto>(o);
                    dto.TrangThai = dto.TrangThaiDauNam;
                    dto.GhiChu = dto.GhiChuDauNam;
                    dto.DinhKemFile = dto.DinhKemFileDauNam;
                    dto.NgayQuyetDinh = dto.NgayQuyetDinhDauNam;
                    dto.DinhKemFile = dto.DinhKemFileDauNam;
                    dto.SoQuyetDinh = dto.SoQuyetDinhDauNam;
                    dto.KeHoachSauBoSung = 0;
                    dto.KeHoachSauBoSungDuocDuyet = 0;
                    dto.LoaiKeHoach = "DAU_NAM";
                    list.Add(dto);
                });
                //dieuchinh
                item.Where(x => !string.IsNullOrWhiteSpace(x.TrangThaiDieuChinh)
                            && (nam == 0 || x.Nam == nam)
                ).ToList().ForEach(o =>
                {
                    var dto = ObjectMapper.Map<KeHoachTongNguon, KeHoachTongNguonDto>(o);
                    dto.TrangThai = dto.TrangThaiDieuChinh;
                    dto.GhiChu = dto.GhiChuDieuChinh;
                    dto.DinhKemFile = dto.DinhKemFileDieuChinh;
                    dto.NgayQuyetDinh = dto.NgayQuyetDinhDieuChinh;
                    dto.DinhKemFile = dto.DinhKemFileDieuChinh;
                    dto.SoQuyetDinh = dto.SoQuyetDinhDieuChinh;
                    dto.LoaiKeHoach = "DIEU_CHINH";
                    list.Add(dto);
                });

                list = list.Where(x => !string.IsNullOrWhiteSpace(x.LoaiKeHoach)
                                && (loaikehoach == "" || x.LoaiKeHoach == loaikehoach)
                                && (trangthai == "" || x.TrangThai == trangthai)).ToList();
            }
            return list;
        }
        [HttpPut]
        [Route("/api/app/KeHoachTongNguonDieuChinh/{id}")]
        public async Task DeleteKeHoachVonDieuChinh(Guid id)
        {
            var item = await _iKeHoachTongNguonRepository.GetAsync(id);
            if (item != null && item.IsDeleted == false)
            {
                item.TrangThaiDieuChinh = string.Empty;
                item.GhiChuDieuChinh = string.Empty;
                item.DinhKemFileDieuChinh = string.Empty;
                item.KeHoachSauBoSung = 0;
                item.KeHoachSauBoSungDuocDuyet = 0;
                item.NgayQuyetDinhDieuChinh = DateTime.MinValue;
                await _iKeHoachTongNguonRepository.UpdateAsync(item, true);
            }
        }
        #endregion
    }
}