using System;
using System.ComponentModel.DataAnnotations;

namespace xdcb.QuanLyVon.KeHoachTongNguonChiTiet.Dtos
{
	/// <summary>
	/// Generated CreateUpdateDto for Table : KeHoachTongNguonChiTiet.
	/// </summary>
	public class CreateUpdateKeHoachTongNguonChiTietDto
	{
		#region Generated By Column

		//[Required]
		public Guid KeHoachTongNguonId { get; set; }

		//[Required]
		public Guid NguonVonId { get; set; }

		//[Required]
		public Guid NguonVonChaId { get; set; }

		//[StringLength(255)]
		public string TenNguonVon { get; set; }

		//[Required]
		public decimal KeHoachDauNamTruoc { get; set; }

		//[Required]
		public decimal KeHoachBoSungNamTruoc { get; set; }

		//[Required]
		public decimal KeHoachDauNam { get; set; }

		//[Required]
		public decimal KeHoachDauNamDuocDuyet { get; set; }

		//[Required]
		public decimal DieuChinhTang { get; set; }

		//[Required]
		public decimal DieuChinhGiam { get; set; }

		//[Required]
		public decimal KeHoachBoSung { get; set; }

		//[Required]
		public decimal KeHoachBoSungDuocDuyet { get; set; }

		//[StringLength(1073741823)]
		public string GhiChuSoDauNam { get; set; }

		//[StringLength(1073741823)]
		public string GhiChuSoDieuChinh { get; set; }

		//[StringLength(1073741823)]
		public string GhiChuUyBanDauNam { get; set; }

		//[StringLength(1073741823)]
		public string GhiChuUyBanDieuChinh { get; set; }

		public bool IsDeleteDieuChinh { get; set; }

		public bool IsSelectDieuChinh { get; set; }

		#endregion
	}
}