using System;
using Volo.Abp.Application.Dtos;

namespace xdcb.QuanLyVon.KeHoachTongNguonChiTiet.Dtos
{
	/// <summary>
	/// Generated Contracts Dto for Table : KeHoachTongNguonChiTiet.
	/// </summary>
	public class KeHoachTongNguonChiTietDto : FullAuditedEntityDto<Guid>
	{
		#region Generated By Column

		public Guid KeHoachTongNguonId { get; set; }

		public Guid NguonVonId { get; set; }

		public Guid NguonVonChaId { get; set; }

		public string TenNguonVon { get; set; }

		public decimal KeHoachDauNamTruoc { get; set; }

		public decimal KeHoachBoSungNamTruoc { get; set; }

		public decimal KeHoachDauNam { get; set; }

		public decimal KeHoachDauNamDuocDuyet { get; set; }

		public decimal DieuChinhTang { get; set; }

		public decimal DieuChinhGiam { get; set; }

		public decimal KeHoachBoSung { get; set; }

		public decimal KeHoachBoSungDuocDuyet { get; set; }

		public string GhiChuSoDauNam { get; set; }

		public string GhiChuSoDieuChinh { get; set; }

		public string GhiChuUyBanDauNam { get; set; }

		public string GhiChuUyBanDieuChinh { get; set; }

		public bool IsDeleteDieuChinh { get; set; }

		public bool IsSelectDieuChinh { get; set; }

		#endregion

		#region ExtraProperty
		public decimal SoSanhDuToan { get; set; }
		public decimal SoSanhBoSung { get; set; }
		public string STT { get; set; }
		public string MaNguonVon { get; set; }
		public int NguonVonIndex { get; set; }
		#endregion
	}
}