using System;
using System.ComponentModel.DataAnnotations;

namespace xdcb.FormServices.ModuleGroup.Dtos
{
	/// <summary>
	/// Generated CreateUpdateDto for Table : ModuleGroup.
	/// </summary>
	public class CreateUpdateModuleGroupDto
	{
		#region Generated By Column

		public string ModuleGroupNo { get; set; }

		public string ModuleGroupName { get; set; }

		#endregion
	}
}